force-app/main/default/objects/ucinn_portal_Job__c/ucinn_portal_Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PORTAL_TRIG_JobHandlerTest.cls
@isTest
public with sharing class PORTAL_TRIG_JobHandlerTest {
    public virtual class TestClass extends PORTAL_TestClassBase{

        public virtual void testGeolocateNewJobs() {
            ucinn_portal_Job__c job = new ucinn_portal_Job__c();
            job.Address_Line_1__c = '2855 Michelle Drive';
            job.Address_Line_2__c = '';
            job.Address_Line_3__c = '';
            job.City__c = 'Irvine';
            job.State__c = 'CA';
            job.Country__c = 'United States';
            job.Postal_Code__c = '92606';
            insert job;
            PORTAL_TRIG_JobHandler.geolocateJobs(new List<ucinn_portal_Job__c>{job});
        }

        public virtual void testGeolocateUpdatedJob() {
            ucinn_portal_Job__c job = new ucinn_portal_Job__c();
            job.Address_Line_1__c = '2855 Michelle Drive';
            job.Address_Line_2__c = '';
            job.Address_Line_3__c = '';
            job.City__c = 'Irvine';
            job.State__c = 'CA';
            job.Country__c = 'United States';
            job.Postal_Code__c = '92606';
            insert job;

            ucinn_portal_Job__c updatedJob = new ucinn_portal_Job__c();
            updatedJob.Id = job.Id;
            updatedJob.Address_Line_1__c = '2855 Michelle Drive';
            updatedJob.Address_Line_2__c = '';
            updatedJob.Address_Line_3__c = '';
            updatedJob.City__c = 'Irvine';
            updatedJob.State__c = 'California';
            updatedJob.Country__c = 'United States';
            updatedJob.Postal_Code__c = '92606';

            PORTAL_TRIG_JobHandler.geolocateJobs(new List<ucinn_portal_Job__c>{job}, new List<ucinn_portal_Job__c>{updatedJob});
        }
        
        public virtual void testRun() {
            PORTAL_TRIG_JobHandler handler = new PORTAL_TRIG_JobHandler();
            List<sObject> oldList = new List<sObject>();
            List<sObject> newList = new List<sObject>();

            Test.startTest();

            handler.run(newList,
                        oldList,
                        ucinn_ascendv2.ascend_TDTM_Runnable.Action.AfterInsert,
                        ucinn_portal_Job__c.getSObjectType().getDescribe());

            handler.run(newList,
                        oldList,
                        ucinn_ascendv2.ascend_TDTM_Runnable.Action.AfterUpdate,
                        ucinn_portal_Job__c.getSObjectType().getDescribe());

            Test.stopTest();
        }

        public virtual void testGeolocateNewJobsCoverageIncrease() {
            ucinn_portal_Job__c job = new ucinn_portal_Job__c();
            job.Address_Line_1__c = '2855 Michelle Drive';
            job.Address_Line_2__c = 'Test';
            job.Address_Line_3__c = 'Test';
            job.City__c = 'Irvine';
            job.State__c = 'CA';
            job.Country__c = 'United States';
            job.Postal_Code__c = '92606';
            insert job;
            PORTAL_TRIG_JobHandler.geolocateJobs(new List<ucinn_portal_Job__c>{job});
        }
    }

    @isTest
    public static void testGeolocateNewJobs() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_JobHandlerTestClass().testGeolocateNewJobs();
    }

    @isTest
    public static void testGeolocateUpdatedJob() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_JobHandlerTestClass().testGeolocateUpdatedJob();
    }

    @isTest
    public static void testRun() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_JobHandlerTestClass().testRun();
    }

    @isTest
    public static void testGeolocateNewJobsCoverageIncrease() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_JobHandlerTestClass().testGeolocateNewJobsCoverageIncrease();
    }
   
}