force-app/main/default/objects/Portal_Page_Section_Setting__mdt/Portal_Page_Section_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Page Section Setting</label>
    <pluralLabel>Portal Page Section Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Page_Section_Setting__mdt/fields/Active_Record_Field_Map__c.field-meta.xml
<CustomField>
    <fullName>Active_Record_Field_Map__c</fullName>
    <description>If we want to display a record on the front end, this field contains a json string of all of the fields and values we need to populate in order to show the record.</description>
    <inlineHelpText>If we want to display a record on the front end, this field contains a json string of all of the fields and values we need to populate in order to show the record.</inlineHelpText>
    <label>Active Record Field Map</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Page_Section_Setting__mdt/fields/Record_Type_Developer_Name__c.field-meta.xml
<CustomField>
    <fullName>Record_Type_Developer_Name__c</fullName>
    <description>The developer name of the record type that we want to populate the record with</description>
    <inlineHelpText>The developer name of the record type that we want to populate the record with</inlineHelpText>
    <label>Record Type Developer Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Page_Section_Setting__mdt/fields/SObject_API_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_API_Name__c</fullName>
    <description>The sobject api name of the records we are trying to query and display on the front end.</description>
    <inlineHelpText>The sobject api name of the records we are trying to query and display on the front end.</inlineHelpText>
    <label>SObject API Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/Portal_Section_Field_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Section Field Setting</label>
    <pluralLabel>Portal Section Field Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>This is the sobject field api name that we wish to query.</description>
    <inlineHelpText>This is the sobject field api name that we wish to query.</inlineHelpText>
    <label>Field API Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Section_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Section_Mapping__c</fullName>
    <description>The parent custom metadata record for this field. This field is a field on the sobject described by the parent record.</description>
    <inlineHelpText>The parent custom metadata record for this field. This field is a field on the sobject described by the parent record.</inlineHelpText>
    <label>Section Mapping</label>
    <referenceTo>Portal_Page_Section_Setting__mdt</referenceTo>
    <relationshipLabel>Portal Section Field Settings</relationshipLabel>
    <relationshipName>Portal_Section_Field_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Staging_Record_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Staging_Record_Field_API_Name__c</fullName>
    <description>The field api name for the staging sobject record that we will populate if we need to create a staging record.</description>
    <inlineHelpText>The field api name for the staging sobject record that we will populate if we need to create a staging record.</inlineHelpText>
    <label>Staging Record Field API Name</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Affiliation__c/ucinn_ascendv2__Affiliation__c.object-meta.xml
<CustomObject>
    <description>A connection between constituents and organizations that can affect gift processing.</description>
    <label>Affiliation</label>
    <nameField>
        <label>Affiliation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Affiliations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Affiliation__c/fields/ucinn_ascendv2__Account__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Account__c</fullName>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations_Account</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Affiliation__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Affiliations</relationshipLabel>
    <relationshipName>Affiliations_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/ucinn_ascendv2__Interim__c.object-meta.xml
<CustomObject>
    <description>The shell object used for Integration that stores the fields for constituents.</description>
    <label>Interim</label>
    <nameField>
        <label>Interim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/fields/ucinn_ascendv2__Account__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Account ID that matches this Interim__C object</description>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interims</relationshipLabel>
    <relationshipName>Interims_Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact ID that matches this Interim__C object</description>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interims</relationshipLabel>
    <relationshipName>Interims_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/ucinn_portal_Interim_Employment__c.object-meta.xml
<CustomObject>
    <label>Interim Employment</label>
    <nameField>
        <label>Interim Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interim Employments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Interim Employments</relationshipLabel>
    <relationshipName>ucinn_portal_Interim_Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Interim__c.field-meta.xml
<CustomField>
    <fullName>Interim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interim</label>
    <referenceTo>ucinn_ascendv2__Interim__c</referenceTo>
    <relationshipLabel>Interim Employments</relationshipLabel>
    <relationshipName>ucinn_portal_Interim_Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Manual_Review_Reason__c.field-meta.xml
<CustomField>
    <fullName>Manual_Review_Reason__c</fullName>
    <label>Manual Review Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PORTAL_BATCH_ProcessInProgressEmployment.cls
/*
 * Copyright (c) 2021, UC Innovation, Inc.  All Rights Reserved.
 *                     https://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */

/**
 * batch class that takes an interim employment and creates an affiliation
 * that links the interim employment account to the interim's contact
 *
 * @author      Ashley Tran
 * @version 1.0
 * @since   1.0
 */
public virtual with sharing class PORTAL_BATCH_ProcessInProgressEmployment implements Database.Batchable<sObject>{

    List<Portal_Page_Section_Setting__mdt> relatedRecordSettingList = new List<Portal_Page_Section_Setting__mdt>();


    /**
     * Constructor that retrieves the custom metadata records that will be used
     * for mapping the interim employment fields to affiliation records
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     */
    public PORTAL_BATCH_ProcessInProgressEmployment() {
        List<Portal_Page_Section_Setting__mdt> pageSectionSettingList = PORTAL_UTIL_PageSectionSetting.getPageSectionSettingRecords('Hiring Manager', '', '');
        for (Portal_Page_Section_Setting__mdt pageSectionSetting : pageSectionSettingList) {
            if (String.isNotBlank(pageSectionSetting.SObject_API_Name__c) && pageSectionSetting.SObject_API_Name__c == 'ucinn_ascendv2__Affiliation__c') {
                relatedRecordSettingList.add(pageSectionSetting);
            }
        }
    }

    /**
     * batch start method that uses the custom metadata records
     * to get the fields that are needed for the query
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     *
     * @return                          the query locator for this batch
     */
    public virtual Database.QueryLocator start(Database.BatchableContext BC) {
        Set<String> fieldsToQuery = new Set<String>();
        for (Portal_Page_Section_Setting__mdt relatedRecordSetting: relatedRecordSettingList) {
            if (relatedRecordSetting.Portal_Section_Field_Settings__r != null) {
                for (Portal_Section_Field_Setting__mdt fieldSetting : relatedRecordSetting.Portal_Section_Field_Settings__r) {
                    if (String.isNotBlank(fieldSetting.Staging_Record_Field_API_Name__c)) {
                        System.debug(fieldSetting.Staging_Record_Field_API_Name__c);
                        fieldsToQuery.add(fieldSetting.Staging_Record_Field_API_Name__c);
                    }
                }
            }
        }
        fieldsToQuery.add('Account__c');
        fieldsToQuery.add('Interim__r.ucinn_ascendv2__Contact__c');
        fieldsToQuery.add('Id');
        String queryString = 'SELECT ' + String.join(new List<String>(fieldsToQuery), ',')  + ' FROM ucinn_portal_Interim_Employment__c '
                            + ' WHERE Status__c = \'In Progress\' AND Account__c != null AND Interim__r.ucinn_ascendv2__Contact__c != null';
        return Database.getQueryLocator(queryString);
    }

    /**
     * execution method that will take a list of interim employment records
     * and create sobjects from them
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     *
     *
     * @param interimEmploymentList             list of interim employments to process in this execution
     */

    public virtual void execute(Database.BatchableContext BC, List<ucinn_portal_Interim_Employment__c> interimEmploymentList) {

        Map<Id, ucinn_ascendv2__Affiliation__c> interimEmploymentIdToAffiliationMap = new Map<Id, ucinn_ascendv2__Affiliation__c>();

        for (ucinn_portal_Interim_Employment__c interimEmployment : interimEmploymentList) {
            ucinn_ascendv2__Affiliation__c eachAffiliationRecord = new ucinn_ascendv2__Affiliation__c();

            for (Portal_Page_Section_Setting__mdt relatedRecordSetting: relatedRecordSettingList) {
                //populate fields
                if (relatedRecordSetting.Portal_Section_Field_Settings__r != null) {
                    for (Portal_Section_Field_Setting__mdt fieldSetting : relatedRecordSetting.Portal_Section_Field_Settings__r) {
                        if (String.isNotBlank(fieldSetting.Staging_Record_Field_API_Name__c) && String.isNotBlank(fieldSetting.Field_API_Name__c)) {
                            eachAffiliationRecord.put(fieldSetting.Field_API_Name__c, interimEmployment.get(fieldSetting.Staging_Record_Field_API_Name__c));
                        }
                    }
                }

                if (String.isNotBlank(relatedRecordSetting.Record_Type_Developer_Name__c)) {
                    Schema.RecordTypeInfo recordTypeInfo =  Schema.getGlobalDescribe().get(eachAffiliationRecord.getSObjectType().getDescribe().getName()).getDescribe().getRecordTypeInfosByDeveloperName().get(relatedRecordSetting.Record_Type_Developer_Name__c);
                    if (recordTypeInfo == null) {
                        System.debug('PORTAL_BATCH_ProcessInProgressEmployment execute record type name is wrong for section ' + relatedRecordSetting.Label);
                    } else {
                        eachAffiliationRecord.put('RecordTypeId', recordTypeInfo.getRecordTypeId());
                    }
                }

                if (String.isNotBlank(relatedRecordSetting.Active_Record_Field_Map__c)) {
                    Map<String, Object> fieldMap = (Map<String, Object>) System.JSON.deserializeUntyped(relatedRecordSetting.Active_Record_Field_Map__c);
                    for (String field : fieldMap.keySet()) {
                        eachAffiliationRecord.put(field, fieldMap.get(field));
                    }
                }
            }
            eachAffiliationRecord.ucinn_ascendv2__Contact__c = interimEmployment.Interim__r.ucinn_ascendv2__Contact__c;
            eachAffiliationRecord.ucinn_ascendv2__Account__c = interimEmployment.Account__c;

            interimEmploymentIdToAffiliationMap.put(interimEmployment.Id, eachAffiliationRecord);
        }

        List<Database.SaveResult> saveResultList = Database.insert(interimEmploymentIdToAffiliationMap.values(), false);
        List<ucinn_portal_Interim_Employment__c> interimEmploymentsToUpdate = new  List<ucinn_portal_Interim_Employment__c>();
        for (Id interimEmploymentId : interimEmploymentIdToAffiliationMap.keyset()) {
            ucinn_portal_Interim_Employment__c interimEmployment = new ucinn_portal_Interim_Employment__c();
            interimEmployment.Id = interimEmploymentId;
            if (String.isNotBlank(interimEmploymentIdToAffiliationMap.get(interimEmploymentId).Id)) {
                interimEmployment.Status__c = PORTAL_CONST_CommunityUser.COMPLETED;
            } else {
                interimEmployment.Status__c = PORTAL_CONST_CommunityUser.MANUAL_REVIEW;
                interimEmployment.Manual_Review_Reason__c += 'Could not create affiliation for this interim employment. ';
            }
            interimEmploymentsToUpdate.add(interimEmployment);
        }

        Database.update(interimEmploymentsToUpdate, false);
    }

    /**
     * finish method for batch class
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     */
    public virtual void finish(Database.BatchableContext BC) {

    }
}