force-app/main/default/objects/Portal_Page_Section_Setting__mdt/Portal_Page_Section_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Page Section Setting</label>
    <pluralLabel>Portal Page Section Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/Portal_Section_Field_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Section Field Setting</label>
    <pluralLabel>Portal Section Field Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Front_End_Field_Id__c.field-meta.xml
<CustomField>
    <fullName>Front_End_Field_Id__c</fullName>
    <description>The unique id that will be used on the front end to display the correct data and can be used as the field name in apex if we want to wrap the class in a custom data structure.</description>
    <inlineHelpText>The unique id that will be used on the front end to display the correct data and can be used as the field name in apex if we want to wrap the class in a custom data structure.</inlineHelpText>
    <label>Front End Field Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Section_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Section_Mapping__c</fullName>
    <description>The parent custom metadata record for this field. This field is a field on the sobject described by the parent record.</description>
    <inlineHelpText>The parent custom metadata record for this field. This field is a field on the sobject described by the parent record.</inlineHelpText>
    <label>Section Mapping</label>
    <referenceTo>Portal_Page_Section_Setting__mdt</referenceTo>
    <relationshipLabel>Portal Section Field Settings</relationshipLabel>
    <relationshipName>Portal_Section_Field_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Staging_Record_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Staging_Record_Field_API_Name__c</fullName>
    <description>The field api name for the staging sobject record that we will populate if we need to create a staging record.</description>
    <inlineHelpText>The field api name for the staging sobject record that we will populate if we need to create a staging record.</inlineHelpText>
    <label>Staging Record Field API Name</label>
    <length>90</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Review_Transaction_v2__c/ucinn_ascendv2__Review_Transaction_v2__c.object-meta.xml
<CustomObject>
    <description>Staging object for pledges, gifts and payments coming from the interfaces that are automatically processed, or can be subject for review.  Version 2.</description>
    <label>Review Transaction (v2)</label>
    <nameField>
        <label>Review Transaction v2 Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Review Transactions (v2)</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_PaymentHubV2ControllerBase.cls
/*
 * Copyright (c) 2023, UC Innovation, Inc.  All Rights Reserved.
 *                     https://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */

/**
 * Base controller that contains functions for different payment methods
 *
 * @author          Phillip Nguyen
 * @version         1.14
 * @since           1.14
 */
public without sharing virtual class PORTAL_PaymentHubV2ControllerBase extends PORTAL_PaymentHubControllerBase {

    /**
     * method that populates the billing information for the review transaction
     *
     *
     * @author: Phillip Nguyen
     * @since: 1.14
     *
     *
     * @param billingInformation:           Map of data that contains the billing information
     * @param reviewTransaction:            The review transaction record we are populating
     * @param pageName                      Section Setting Page Name
     *
     */
    protected virtual override void populateBillingInformation(ucinn_ascendv2__Review_Transaction_v2__c reviewTransaction, Map<String, Object> billingInformation, String pageName) {
        if (reviewTransaction == null || billingInformation == null || billingInformation.isEmpty() || String.isBlank(pageName)) {
            return;
        }

        List<Portal_Page_Section_Setting__mdt> sectionSettingList = PORTAL_UTIL_PageSectionSetting.getPageSectionSettingRecords(pageName, '', '');

        for (Portal_Page_Section_Setting__mdt eachSection : sectionSettingList) {
            if (eachSection.Portal_Section_Field_Settings__r == null) {
                continue;
            }

            for (Portal_Section_Field_Setting__mdt eachField : eachSection.Portal_Section_Field_Settings__r) {
                if (String.isBlank(eachField.Staging_Record_Field_API_Name__c) || String.isBlank(eachField.Front_End_Field_Id__c) || String.isBlank((String)billingInformation.get(eachField.Front_End_Field_Id__c))) {
                    continue;
                }

                reviewTransaction.put(eachField.Staging_Record_Field_API_Name__c, billingInformation.get(eachField.Front_End_Field_Id__c));
            }
        }
    }

}