force-app/main/default/objects/Portal_Page_Section_Setting__mdt/Portal_Page_Section_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Page Section Setting</label>
    <pluralLabel>Portal Page Section Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Page_Section_Setting__mdt/fields/Page_Main_Section__c.field-meta.xml
<CustomField>
    <fullName>Page_Main_Section__c</fullName>
    <description>The main header that we are displaying the records under on the portal page</description>
    <inlineHelpText>The main header that we are displaying the records under on the portal page</inlineHelpText>
    <label>Page Main Section</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Personal_Information</fullName>
            </value>
            <value>
                <fullName>Phones</fullName>
            </value>
            <value>
                <fullName>Emails</fullName>
            </value>
            <value>
                <fullName>Addresses</fullName>
            </value>
            <value>
                <fullName>Degrees</fullName>
            </value>
            <value>
                <fullName>Employment</fullName>
            </value>
            <value>
                <fullName>Social_Media</fullName>
            </value>
            <value>
                <fullName>Privacy_Settings</fullName>
            </value>
            <value>
                <fullName>Designations</fullName>
            </value>
            <value>
                <fullName>Giving History Table</fullName>
            </value>
            <value>
                <fullName>Pledge table</fullName>
            </value>
            <value>
                <fullName>Matching Gift Table</fullName>
            </value>
            <value>
                <fullName>Recurring Gift Table</fullName>
            </value>
            <value>
                <fullName>Yearly Giving Table</fullName>
            </value>
            <value>
                <fullName>Year End Tax Letter</fullName>
            </value>
            <value>
                <fullName>Yearly Giving Summary Table</fullName>
            </value>
            <value>
                <fullName>Events Tabs</fullName>
            </value>
            <value>
                <fullName>Content Submission Form</fullName>
            </value>
            <value>
                <fullName>Submitted Content</fullName>
            </value>
            <value>
                <fullName>Company_Information</fullName>
            </value>
            <value>
                <fullName>Giving History Gift Receipt</fullName>
            </value>
            <value>
                <fullName>Pie chart</fullName>
            </value>
            <value>
                <fullName>Giving Societies List</fullName>
            </value>
            <value>
                <fullName>Giving Societies Banner</fullName>
            </value>
            <value>
                <fullName>Donor Story</fullName>
            </value>
            <value>
                <fullName>Detail Page</fullName>
            </value>
            <value>
                <fullName>Society Membership Table</fullName>
            </value>
            <value>
                <fullName>Zone Search</fullName>
            </value>
            <value>
                <fullName>Zone Leadership</fullName>
            </value>
            <value>
                <fullName>Featured Zone Members</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Page_Section_Setting__mdt/fields/Page_Name__c.field-meta.xml
<CustomField>
    <fullName>Page_Name__c</fullName>
    <description>The portal page name that we are displaying the records on</description>
    <inlineHelpText>The portal page name that we are displaying the records on</inlineHelpText>
    <label>Page Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bio Information</fullName>
                <default>true</default>
                <label>Bio Information</label>
            </value>
            <value>
                <fullName>In Progress Interim</fullName>
            </value>
            <value>
                <fullName>Interim Company</fullName>
            </value>
            <value>
                <fullName>My Information</fullName>
            </value>
            <value>
                <fullName>Online Giving</fullName>
            </value>
            <value>
                <fullName>My Information Self Report</fullName>
            </value>
            <value>
                <fullName>Giving Societies</fullName>
            </value>
            <value>
                <fullName>Giving History</fullName>
            </value>
            <value>
                <fullName>Year end tax letter</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>Event Submission Form</fullName>
            </value>
            <value>
                <fullName>Submitted Content</fullName>
            </value>
            <value>
                <fullName>New User Login</fullName>
            </value>
            <value>
                <fullName>Hiring Manager</fullName>
            </value>
            <value>
                <fullName>Gift Receipt</fullName>
            </value>
            <value>
                <fullName>Yearly Tax letter Table</fullName>
            </value>
            <value>
                <fullName>Giving Societies Detail</fullName>
            </value>
            <value>
                <fullName>Zone Home Page</fullName>
            </value>
            <value>
                <fullName>Zone Bio Detail</fullName>
            </value>
            <value>
                <fullName>Zone Leadership</fullName>
            </value>
            <value>
                <fullName>Zone Memberships</fullName>
            </value>
            <value>
                <fullName>Zone Search</fullName>
            </value>
            <value>
                <fullName>Job Posting</fullName>
            </value>
            <value>
                <fullName>Job Management</fullName>
            </value>
            <value>
                <fullName>Job Listing</fullName>
            </value>
            <value>
                <fullName>Job Application</fullName>
            </value>
            <value>
                <fullName>My Applications</fullName>
            </value>
            <value>
                <fullName>Job Applicants</fullName>
            </value>
            <value>
                <fullName>Job Search</fullName>
            </value>
            <value>
                <fullName>Membership Purchase</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/Portal_Section_Field_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Portal Section Field Setting</label>
    <pluralLabel>Portal Section Field Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>This is the sobject field api name that we wish to query.</description>
    <inlineHelpText>This is the sobject field api name that we wish to query.</inlineHelpText>
    <label>Field API Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Front_End_Field_Id__c.field-meta.xml
<CustomField>
    <fullName>Front_End_Field_Id__c</fullName>
    <description>The unique id that will be used on the front end to display the correct data and can be used as the field name in apex if we want to wrap the class in a custom data structure.</description>
    <inlineHelpText>The unique id that will be used on the front end to display the correct data and can be used as the field name in apex if we want to wrap the class in a custom data structure.</inlineHelpText>
    <label>Front End Field Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Is_Display_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>Is_Display_On_Portal__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If this field is checked, we will display the field on the front end portal page.</description>
    <inlineHelpText>If this field is checked, we will display the field on the front end portal page.</inlineHelpText>
    <label>Is Display On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Portal_Section_Field_Setting__mdt/fields/Section_Mapping__c.field-meta.xml
<CustomField>
    <fullName>Section_Mapping__c</fullName>
    <description>The parent custom metadata record for this field. This field is a field on the sobject described by the parent record.</description>
    <inlineHelpText>The parent custom metadata record for this field. This field is a field on the sobject described by the parent record.</inlineHelpText>
    <label>Section Mapping</label>
    <referenceTo>Portal_Page_Section_Setting__mdt</referenceTo>
    <relationshipLabel>Portal Section Field Settings</relationshipLabel>
    <relationshipName>Portal_Section_Field_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/ucinn_portal_Listing__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Actual_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date_Time__c</fullName>
    <inlineHelpText>Format as YYYY-MM-DD HH:MM:SS and time should be formatted in 24-hour format</inlineHelpText>
    <label>Actual Start Date/Time</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Cache_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Cache_API_Name__c</fullName>
    <label>Cache API Name</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Is_Newsletter_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Newsletter_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Newsletter Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Newsletter_Metrics__c.field-meta.xml
<CustomField>
    <fullName>Newsletter_Metrics__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Newsletter Metrics</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipLabel>Listings</relationshipLabel>
    <relationshipName>ucinn_portal_Listings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Portal_Zone__c.field-meta.xml
<CustomField>
    <fullName>Portal_Zone__c</fullName>
    <label>Portal Zone</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Portal_Zone</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Unpublished</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Subject_Line__c.field-meta.xml
<CustomField>
    <fullName>Subject_Line__c</fullName>
    <label>Subject Line</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Time_Zone__c.field-meta.xml
<CustomField>
    <fullName>Time_Zone__c</fullName>
    <label>Time Zone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Time_Zones</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Newsletter.recordType-meta.xml
<RecordType>
    <fullName>Newsletter</fullName>
    <active>true</active>
    <label>Newsletter</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Search_Filter_Cache__c/ucinn_portal_Search_Filter_Cache__c.object-meta.xml
<CustomObject>
    <label>Search Filter Cache</label>
    <nameField>
        <label>Search Filter Cache Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Search Filter Caches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Search_Filter_Cache__c/fields/Cache_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Cache_API_Name__c</fullName>
    <label>Cache API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/ucinn_portal_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Zone__c/fields/Is_Display_on_Portal__c.field-meta.xml
<CustomField>
    <fullName>Is_Display_on_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display on Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app/main/default/globalValueSets/Portal_Zone.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
        <default>true</default>
        <label>All</label>
    </customValue>
    <customValue>
        <fullName>Main</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni Club of Irvine</fullName>
    </customValue>
    <masterLabel>Portal Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_BATCH_SendNewsletter.cls
/*
* Copyright (c) 2021, UC Innovation, Inc.  All Rights Reserved.
*                     http://www.ucinnovation.com
*
* This source code is licensed, not sold, and is subject to a written
* license agreement.  Among other things, no portion of this source
* code may be copied, transmitted, disclosed, displayed, distributed,
* translated, used as the basis for a derivative work, or used, in
* whole or in part, for any program or purpose other than its intended
* use in compliance with the license agreement as part of UC Innovation's
* software.  This source code and certain of the algorithms contained
* within it are confidential trade secrets of UC Innovation, Inc.
* and may not be used as the basis for any other
* software, hardware, product or service.
*/

/**
* Batch that will send a list of contacts and newsletter information to the
* transactional email api
*
* @author:  Ashley Tran
* @version: 1.0
* @since:   1.0
*/
global virtual without sharing class PORTAL_BATCH_SendNewsletter implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {

    global Id newsletterId;
    global String contactQueryString = '';
    global Datetime deliveryTime;
    global static final String EMAIL_STATUS_FIELD = 'ucinn_portal_Email_Status__c';
    global static final String ERROR_STATUS = 'Error';
    global static final String SENT_STATUS = 'Sent';
    global Integer failures = 0;

    public class SendNewsletterException extends Exception {}

     /**
    * constructor for the newsletter batch
    *
    * @param newsletterId                       The id of the newsletter we are trying to send
    * @param deliveryTime                       The time we want to deliver the newsletter

    * @author:                                 Ashley Tran
    * @since:                                  1.0
    */
    global PORTAL_BATCH_SendNewsletter (Id newsletterId, Datetime deliveryTime){
        if (newsletterId == null || deliveryTime == null) {
            throw new SendNewsletterException('Invalid paramters recieved. Error code: 201');
        }
        this.deliveryTime = deliveryTime;
        this.newsletterId = newsletterId;
        generateContactQuery();
    }

     /**
    * Creates the query that gahers merge fields from the contact in order to pass the merge fields
    * to the email api
    *
    *
    * @author:                                 Ashley Tran
    * @since:                                  1.0
    */

    public void generateContactQuery() {
        List<Portal_Page_Section_Setting__mdt> sectionSettingList = [SELECT Id, (SELECT Field_API_Name__c, Front_End_Field_Id__c
                                                                        FROM Portal_Section_Field_Settings__r)
                                                                        FROM Portal_Page_Section_Setting__mdt
                                                                        WHERE Page_Name__c = :PORTAL_CONST_Newsletter.NEWSLETTER_SUBMISSION_PAGE_NAME
                                                                        AND Page_Main_Section__c = :PORTAL_CONST_Newsletter.MERGE_FIELDS_MAIN_SECTION];

        Set<String> contactFieldSet = new Set<String>();
        for (Portal_Page_Section_Setting__mdt sectionSetting : sectionSettingList) {
            if (sectionSetting.Portal_Section_Field_Settings__r != null) {
                for (Portal_Section_Field_Setting__mdt fieldSetting : sectionSetting.Portal_Section_Field_Settings__r) {
                    if (String.isNotBlank(fieldSetting.Field_API_Name__c)) {
                        contactFieldSet.add(fieldSetting.Field_API_Name__c);
                    }
                }
            }
        }

        contactFieldSet.add('Email');
        contactFieldSet.add('Id');

        this.contactQueryString = 'SELECT ' + String.join(new List<String>(contactFieldSet), ',') + ' FROM Contact WHERE Id IN :contactIdSet and Email != null';
    }


     /**
    * Creates the query locator for the campaign members for the specific newsletter campaign
    *
    * @author:                                 Ashley Tran
    * @since:                                  1.0
    */
    global virtual Database.QueryLocator start(Database.BatchableContext context) {
        Id campaignId = [SELECT Newsletter_Metrics__c FROM ucinn_portal_Listing__c WHERE Id =:this.newsletterId]?.Newsletter_Metrics__c;
        if (campaignId == null) {
            throw new AuraHandledException('There is no newsletter metrics for this newsletter.');
        }
        String queryString = 'SELECT ContactId FROM CampaignMember WHERE CampaignId = :campaignId AND ucinn_portal_Email_Status__c != \'Sent\'';
        return Database.getQueryLocator(queryString);
    }

    /**
    * Gathers the list of campaign members and newsletter parameters to send to the email api
    *
    * @param campaignMemberList                The list of campaign members that need to be sent newsletters
    *
    * @author:                                 Ashley Tran
    * @since:                                  1.0
    */
    global virtual void execute (Database.BatchableContext context, List<sObject> campaignMemberList) {

        Set<Id> contactIdSet = new Set<Id>();

        for (sObject member : campaignMemberList) {
            if (member.get('ContactId') != null) {
                contactIdSet.add((Id) member.get('ContactId'));
            }
        }

        List<Contact> contactList = Database.query(this.contactQueryString);

        List<ucinn_portal_Listing__c> newsletterList = [SELECT Subject_Line__c, Portal_Zone__c FROM ucinn_portal_Listing__c WHERE Id =: this.newsletterId];

        ucinn_portal_Listing__c newsletter = null;
        ucinn_portal_Zone__c zone = null;

        // get club from email, from name, and reply email
        if (!newsletterList.isEmpty()) {
            newsletter = newsletterList.get(0);
            List<ucinn_portal_Zone__c> zones = [SELECT Name, Email__c FROM ucinn_portal_Zone__c WHERE Name =: newsletter.Portal_Zone__c AND Is_Display_on_Portal__c = true];
            if (!zones.isEmpty()) {
                zone = zones[0];
            }
        }

        if (newsletter == null) {
            throw new SendNewsletterException('Could not find newsletter with id: ' + this.newsletterId);
        }

        if (zone == null) {
            throw new SendNewsletterException('There was an issue with your zone, please check your zone. Error Code: 204');
        }

        Map<String, Object> params = new Map<String, Object>();
        params.put(PORTAL_API_EmailHubBase.CONTACT_LIST_KEY, contactList);
        params.put(PORTAL_API_EmailHubBase.FROM_EMAIL_KEY, zone.Email__c);
        params.put(PORTAL_API_EmailHubBase.NEWSLETTER_ID_KEY, this.newsletterId);
        params.put(PORTAL_API_EmailHubBase.ZONE_NAME_KEY, zone.Name);
        params.put(PORTAL_API_EmailHubBase.SUBJECT_KEY, newsletter.Subject_Line__c);
        PORTAL_NewsletterControllerBase controller = (PORTAL_NewsletterControllerBase)PORTAL_Utils.getControllerFactory().getNewsletterController();
        params.put(PORTAL_API_EmailHubBase.HTML_KEY, controller.parseNewsletterHTML(new Map<String, Object>{PORTAL_NewsletterControllerBase.NEWSLETTER_ID_KEY => this.newsletterId}));
        params.put(PORTAL_API_EmailHubBase.PLAIN_TEXT_KEY, controller.parseNewsletterPlainText(new Map<String, Object>{PORTAL_NewsletterControllerBase.NEWSLETTER_ID_KEY => this.newsletterId}));
        params.put(PORTAL_API_EmailHubBase.DELIVERY_TIME_KEY, this.deliveryTime);

        try {
            PORTAL_CommunityUtils.throwTestException(null);

            PORTAL_API_EmailHubBase.scheduleTransactionalEmail(params);
            for (SObject member : campaignMemberList) {
                member.put(EMAIL_STATUS_FIELD, SENT_STATUS);
            }
            update campaignMemberList;

        } catch (Exception e) {
            System.debug('Error: ' + e);
            for (sObject member : campaignMemberList) {
                member.put(EMAIL_STATUS_FIELD, ERROR_STATUS);
            }
            update campaignMemberList;
            this.failures += 1;
        }

    }

    /*
    * Calls the next set of caches to run if there are more caches, if not updates the newsletter to state it has finished.
    * Calls next batch to avoid heap spaces if there are alot of id's in the cache.
    *
    * @param bc                                                 Context of batch provided by salesforce
    */
    global virtual void finish(Database.BatchableContext bc) {

        ucinn_portal_Listing__c newsletter = [SELECT Id, Actual_Start_Date_Time__c, Cache_API_Name__c, Time_Zone__c from ucinn_portal_Listing__c WHERE Id=: this.newsletterId];
        if (failures > 0 || [SELECT NumberOfErrors FROM AsyncApexJob WHERE Id = :bc.getJobId()]?.NumberOfErrors > 0) {
            newsletter.Status__c = 'Incomplete';
        } else if (this.deliveryTime < Datetime.now().addMinutes(30)) {
            newsletter.Is_Newsletter_Sent__c = true;
            newsletter.Status__c = 'Published';
        } else {
            newsletter.Status__c = 'Scheduled';
            newsletter.Start_Date_Time__c = this.deliveryTime;
        }

        // set the time it was sent

        newsletter.Actual_Start_Date_Time__c = String.valueOf(DateTime.now());
        if (String.isBlank(newsletter.Time_Zone__c)) {
            newsletter.Time_Zone__c = PORTAL_CONST_Global.DEFAULT_TIME_ZONE;
        }

        update newsletter;

        if (String.isNotBlank( newsletter.Cache_API_Name__c)) {
            delete [SELECT Id FROM ucinn_portal_Search_Filter_Cache__c WHERE Cache_API_Name__c =: newsletter.Cache_API_Name__c];
        }

    }

}