force-app/main/default/objects/ucinn_ascendv2__Phone__c/ucinn_ascendv2__Phone__c.object-meta.xml
<CustomObject>
    <description>The phone numbers of the constituent or organization.</description>
    <label>Phone</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Phones</relationshipLabel>
    <relationshipName>Phones_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/fields/ucinn_ascendv2__Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Phone_Number__c</fullName>
    <label>Phone Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/fields/ucinn_ascendv2__Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ucinn_ascendv2__Phone_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ucinn_ascendv2__Phone_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Home - Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Home - Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Home - Landline</fullName>
    </customValue>
    <customValue>
        <fullName>Home - Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Landline</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Unknown</fullName>
    </customValue>
    <customValue>
        <fullName>Organization - Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect/Donor Request to Remove</fullName>
    </customValue>
    <customValue>
        <fullName>Removed Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Address - Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Address - Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Address - Landline</fullName>
    </customValue>
    <customValue>
        <fullName>Alternate Address - Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni Association Membership - Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni Association Membership - Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni Association Membership - Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Assistant</fullName>
        <label>Assistant/Contact</label>
    </customValue>
    <customValue>
        <fullName>Business - Business</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Foreign</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Foreign Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Business - Foreign Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment Reporting - Cell</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment Reporting - Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment Reporting - Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Fax</fullName>
    </customValue>
    <customValue>
        <fullName>Foreign</fullName>
    </customValue>
    <masterLabel>Phone Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_MyInformationControllerBaseTestOR.cls
public class PORTAL_MyInformationControllerBaseTestOR extends PORTAL_MyInformationControllerBaseTest.TestClass{
	
    public override void createPhones() {
        
        List<ucinn_ascendv2__Phone__c> phones = new List<ucinn_ascendv2__Phone__c>();
        
        ucinn_ascendv2__Phone__c homePhone = new ucinn_ascendv2__Phone__c();
        homePhone.ucinn_ascendv2__Phone_Number__c = '9876543210';
        homePhone.ucinn_ascendv2__Type__c = 'Home - Phone';
        homePhone.ucinn_ascendv2__Is_Preferred__c = true;
        homePhone.ucinn_ascendv2__Status__c = 'Current';
        homePhone.ucinn_ascendv2__Contact__c = con.Id;
        homePhone.ucinn_portal_Is_Display_On_Portal__c = true;
        homePhone.RecordTypeId = Schema.SObjectType.ucinn_ascendv2__Phone__c.getRecordTypeInfosByDeveloperName().get('Contact_Phone').getRecordTypeId();
        homePhone = (ucinn_ascendv2__Phone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => homePhone});
        phones.add(homePhone);
        
        ucinn_ascendv2__Phone__c inactivePhone = new ucinn_ascendv2__Phone__c();
        inactivePhone.ucinn_ascendv2__Phone_Number__c = '5555555555';
        inactivePhone.ucinn_ascendv2__Type__c = 'Home - Phone';
        inactivePhone.ucinn_ascendv2__Is_Preferred__c = false;
        inactivePhone.ucinn_ascendv2__Status__c = 'Inactive';
        inactivePhone.ucinn_ascendv2__Contact__c = con.Id;
        inactivePhone.ucinn_portal_Is_Display_On_Portal__c = true;
        inactivePhone.RecordTypeId = Schema.SObjectType.ucinn_ascendv2__Phone__c.getRecordTypeInfosByDeveloperName().get('Contact_Phone').getRecordTypeId();
        inactivePhone = (ucinn_ascendv2__Phone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => inactivePhone});
        phones.add(inactivePhone);
        
        ucinn_ascendv2__Phone__c mobilePhone = new ucinn_ascendv2__Phone__c();
        mobilePhone.ucinn_ascendv2__Phone_Number__c = '9876543210';
        mobilePhone.ucinn_ascendv2__Type__c = 'Home - Landline';
        mobilePhone.ucinn_ascendv2__Is_Preferred__c = false;
        mobilePhone.ucinn_ascendv2__Status__c = 'Current';
        mobilePhone.ucinn_ascendv2__Contact__c = con.Id;
        mobilePhone.ucinn_portal_Is_Display_On_Portal__c = true;
        mobilePhone.RecordTypeId = Schema.SObjectType.ucinn_ascendv2__Phone__c.getRecordTypeInfosByDeveloperName().get('Contact_Phone').getRecordTypeId();
        mobilePhone = (ucinn_ascendv2__Phone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => mobilePhone});
        phones.add(mobilePhone);
        
        ucinn_ascendv2__Phone__c businessPhone = new ucinn_ascendv2__Phone__c();
        businessPhone.ucinn_ascendv2__Phone_Number__c = '9876543210';
        businessPhone.ucinn_ascendv2__Type__c = 'Business - Cell';
        businessPhone.ucinn_ascendv2__Is_Preferred__c = false;
        businessPhone.ucinn_ascendv2__Status__c = 'Current';
        businessPhone.ucinn_portal_Is_Display_On_Portal__c = true;
        businessPhone.ucinn_ascendv2__Contact__c = con.Id;
        businessPhone.RecordTypeId = Schema.SObjectType.ucinn_ascendv2__Phone__c.getRecordTypeInfosByDeveloperName().get('Contact_Phone').getRecordTypeId();
        businessPhone = (ucinn_ascendv2__Phone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => businessPhone});
        phones.add(businessPhone);
        
        insert phones;
        
        
    }

}