force-app/main/default/objects/ucinn_ascendv2__Contact_Name__c/ucinn_ascendv2__Contact_Name__c.object-meta.xml
<CustomObject>
    <description>The names of the constituent.</description>
    <label>Constituent Name</label>
    <nameField>
        <label>Constituent Name ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Constituent Names</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Contact_Name__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Constituent Names</relationshipLabel>
    <relationshipName>Contact_Names_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Contact_Name__c/fields/ucinn_ascendv2__First_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__First_Name__c</fullName>
    <label>First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Contact_Name__c/fields/ucinn_ascendv2__Last_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Last_Name__c</fullName>
    <label>Last Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Contact_Name__c/fields/ucinn_ascendv2__Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Birth Name</fullName>
            </value>
            <value>
                <fullName>Full Name</fullName>
                <label>Current/Active Name</label>
            </value>
            <value>
                <fullName>Directory</fullName>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Graduation Name</fullName>
            </value>
            <value>
                <fullName>Nickname</fullName>
            </value>
            <value>
                <fullName>Other Name</fullName>
            </value>
            <value>
                <fullName>Potential</fullName>
            </value>
            <value>
                <fullName>Used to Delete a name</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/ucinn_ascendv2__Email__c.object-meta.xml
<CustomObject>
    <description>The emails of the constituent.</description>
    <label>Email</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Email_Address__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ucinn_ascendv2__Email_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/ucinn_ascendv2__Org_Wide_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Org Wide Configuration</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status addresses of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Addresses Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status phones of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Phones Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/ucinn_ascendv2__Email_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Alumni Association Membership</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant/Contact</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Campus</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Home</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect/Donor Request to Remove</fullName>
    </customValue>
    <customValue>
        <fullName>Organization</fullName>
    </customValue>
    <customValue>
        <fullName>Other 1</fullName>
    </customValue>
    <customValue>
        <fullName>Other 2</fullName>
    </customValue>
    <customValue>
        <fullName>Other 3</fullName>
    </customValue>
    <customValue>
        <fullName>Pledge Reminder</fullName>
    </customValue>
    <customValue>
        <fullName>Potential</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Removed Per Request</fullName>
        <label>Removed Email</label>
    </customValue>
    <customValue>
        <fullName>Secondary E-mail</fullName>
    </customValue>
    <customValue>
        <fullName>Second Business</fullName>
    </customValue>
    <customValue>
        <fullName>Personal</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
        <isActive>false</isActive>
        <label>Other</label>
    </customValue>
    <customValue>
        <fullName>Second Home</fullName>
        <isActive>false</isActive>
        <label>Second Home</label>
    </customValue>
    <customValue>
        <fullName>Third Home</fullName>
        <isActive>false</isActive>
        <label>Third Home</label>
    </customValue>
    <customValue>
        <fullName>Fourth Home</fullName>
        <isActive>false</isActive>
        <label>Fourth Home</label>
    </customValue>
    <customValue>
        <fullName>Alternate Address</fullName>
        <isActive>false</isActive>
        <label>Alternate Address</label>
    </customValue>
    <masterLabel>Email Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_SocialLoginControllerTest.cls
@isTest
public with sharing class PORTAL_SocialLoginControllerTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public Auth.UserData userData;
        public Account acct;
        public Contact con;
        public String portalId;
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void setupData() {
            System.runAs(thisUser) {
                ucinn_ascendv2__Org_Wide_Configuration__c customSetting = new ucinn_ascendv2__Org_Wide_Configuration__c(name='Default Org Wide Config', ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c = true,
                                                                                                                        ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c = true);

                customSetting = (ucinn_ascendv2__Org_Wide_Configuration__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => customSetting});
                insert customSetting;
                Id recordType = [SELECT Id, Name FROM RecordType WHERE Name = 'Household'].Id;

                Account accountPortalAccount = new Account(Name = 'ascend Portal Account');
                accountPortalAccount = (Account)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => accountPortalAccount});
                insert accountPortalAccount;

                acct = new Account(Name = 'asad', RecordTypeId = recordType);
                acct = (Account)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => acct});
                insert acct;

                con = new Contact(LastName = 'Test', Email = 'test@ucinnovation.com', AccountId = acct.Id);
                con = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => con});
                insert con;

                ucinn_ascendv2__Email__c email1 = new ucinn_ascendv2__Email__c(ucinn_ascendv2__Contact__c = con.Id,
                                                                            ucinn_ascendv2__Email_Address__c = 'test@ucinnovation.com',
                                                                            ucinn_ascendv2__Type__c = 'Business',
                                                                            ucinn_ascendv2__Status__c = 'Current');

                email1 = (ucinn_ascendv2__Email__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => email1});
                insert email1;
                userData = new Auth.UserData('testIdentifier', 'FirstName', 'LastName', 'FirstName LastName', 'test@ucinnovation.com', 'https://www.ucinnovation.com/test', 'test@ucinnovation.com', 'us', 'ucinnovation', null, new Map<String, String>());
            }
        }

        public virtual void runCreateUser() {
            setupData();

            PORTAL_SocialLoginController authHandler = new PORTAL_SocialLoginController();
            authHandler.createUser(null, userData);
            User u = authHandler.createUser(null, userData);
            u = (User)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => u});
            insert u;

            userData.attributeMap = new Map<String, String>{'sfdc_networkid' => 'testId'};
            authHandler.createUser(null, userData);
            delete con;
            try {
                authHandler.createUser(null, userData);
            } catch (Exception e) {}

            authHandler.updateUser(u.Id, null, userData);
        }

        public virtual void testGetNamesCases() {
            setupData();

            PORTAL_SocialLoginController controller = new PORTAL_SocialLoginController();

            List<sObject> networkIds = [SELECT Id FROM network];
            
            Test.startTest();

            if (networkIds.size() > 0) {
                userData.attributeMap = new Map<String, String>{'sfdc_networkid' => networkIds[0].Id};
            }
            else {
                userData.attributeMap = new Map<String, String>{'sfdc_networkid' => 'Unable to reach code'};
            }
            controller.createUser(null, userData);

            userData.firstName = '';
            userData.lastName = '';
            userData.fullName = 'Test';
            
            controller.createUser(null, userData);


            userData.firstName = '';
            userData.lastName = '';
            userData.fullName = 'Test Name';
            
            controller.createUser(null, userData);


            userData.firstName = '';
            userData.lastName = '';
            userData.fullName = 'Test Test Name';
            
            controller.createUser(null, userData);

            Contact con2 = new Contact(LastName = 'Test2', Email = 'test2@ucinnovation.com', AccountId = acct.Id);
            con2 = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => con2});
            insert con2;
            
            ucinn_ascendv2__Email__c email2 = new ucinn_ascendv2__Email__c(ucinn_ascendv2__Contact__c = con2.Id, 
                                                                           ucinn_ascendv2__Email_Address__c = 'test@ucinnovation.com', 
                                                                           ucinn_ascendv2__Type__c = 'Business', 
                                                                           ucinn_ascendv2__Status__c = 'Current');
    
            email2 = (ucinn_ascendv2__Email__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => email2});
            insert email2;

            ucinn_ascendv2__Contact_Name__c testRelation = new ucinn_ascendv2__Contact_Name__c();
            testRelation.ucinn_ascendv2__Contact__c = con2.Id;
            testRelation.ucinn_ascendv2__Last_Name__c = 'Test';
            insert testRelation;

            try {
                controller.createUser(null, userData);
            } catch (Exception e) {
                System.debug(e);
            }

            Test.stopTest();
        }

        public virtual void testCreateUserContactListCase() {
            setupData();

            PORTAL_SocialLoginController controller = new PORTAL_SocialLoginController();

            List<sObject> networkIds = [SELECT Id FROM network];
            
            Test.startTest();

            if (networkIds.size() > 0) {
                userData.attributeMap = new Map<String, String>{'sfdc_networkid' => networkIds[0].Id};
            }
            else {
                userData.attributeMap = new Map<String, String>{'sfdc_networkid' => 'Unable to reach code'};
            }
            
            controller.createUser(null, userData);

            Contact con2 = new Contact(LastName = 'Test2', Email = 'test2@ucinnovation.com', AccountId = acct.Id);
            con2 = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => con2});
            insert con2;
            
            ucinn_ascendv2__Email__c email2 = new ucinn_ascendv2__Email__c(ucinn_ascendv2__Contact__c = con2.Id, 
                                                                           ucinn_ascendv2__Email_Address__c = 'test@ucinnovation.com', 
                                                                           ucinn_ascendv2__Type__c = 'Business', 
                                                                           ucinn_ascendv2__Status__c = 'Current');
    
            email2 = (ucinn_ascendv2__Email__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => email2});
            insert email2;

            ucinn_ascendv2__Contact_Name__c testRelation = new ucinn_ascendv2__Contact_Name__c();
            testRelation.ucinn_ascendv2__Contact__c = con.Id;
            testRelation.ucinn_ascendv2__First_Name__c = 'FirstName';
            testRelation.ucinn_ascendv2__Last_Name__c = 'LastName';
            insert testRelation;

            ucinn_ascendv2__Contact_Name__c testRelation2 = new ucinn_ascendv2__Contact_Name__c();
            testRelation2.ucinn_ascendv2__Contact__c = con2.Id;
            testRelation.ucinn_ascendv2__First_Name__c = 'FirstName';
            testRelation2.ucinn_ascendv2__Last_Name__c = 'LastName';
            insert testRelation2;

            try {
                controller.createUser(null, userData);
            } catch (Exception e) {
                System.debug(e);
            }

            Test.stopTest();
        }
    }

    static testMethod void runCreateUser() {
        PORTAL_TestClassFactory.getTestClassFactory().getSocialLoginControllerTestClass().runCreateUser();
    }

    static testMethod void testGetNamesCases() {
        PORTAL_TestClassFactory.getTestClassFactory().getSocialLoginControllerTestClass().testGetNamesCases();
    }

    static testMethod void testCreateUserContactListCase() {
        PORTAL_TestClassFactory.getTestClassFactory().getSocialLoginControllerTestClass().testCreateUserContactListCase();
    }
}