force-app/main/default/objects/ucinn_portal_Volunteer_Job__c/ucinn_portal_Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer_Job__c/fields/Is_Reminder_Email_Sent__c.field-meta.xml
<CustomField>
    <fullName>Is_Reminder_Email_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Reminder Email Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/ucinn_portal_Volunteer_Shift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <label>Volunteer Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Reminder_Email_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Email_Date_Time__c</fullName>
    <label>Reminder Email Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Reminder_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Email_Template__c</fullName>
    <label>Reminder Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PORTAL_CONST_Volunteers.cls
public inherited sharing class PORTAL_CONST_Volunteers {
    public static final String VOLUNTEER_HOURS_OBJECT_API_NAME = 'ucinn_portal_Volunteer_Hours__c';
    public static final String VOLUNTEER_SHIFT_OBJECT_API_NAME = 'ucinn_portal_Volunteer_Shift__c';
    public static final String VOLUNTEER_JOB_OBJECT_API_NAME = 'ucinn_portal_Volunteer_Job__c';

    public static final String REMINDER_EMAIL_DATE_TIME_API_NAME = 'Reminder_Email_Date_Time__c';
    public static final String REMINDER_EMAIL_TEMPLATE_API_NAME = 'Reminder_Email_Template__c';
    public static final String IS_REMINDER_EMAIL_SENT_API_NAME = 'Is_Reminder_Email_Sent__c';

    public static final String VOLUNTEER_STATUS_COMPLETED = 'Completed';

    public static final String DEFAULT_EMAIL_SENDER_NAME = 'Volunteer Notification';
}