force-app/main/default/objects/ucinn_portal_Volunteer_Job__c/ucinn_portal_Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer_Job__c/fields/Actual_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date_Time__c</fullName>
    <inlineHelpText>Format as YYYY-MM-DD HH:MM:SS and time should be formatted in 24-hour format</inlineHelpText>
    <label>Actual End Date Time</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Job__c/fields/Actual_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date_Time__c</fullName>
    <inlineHelpText>Format as YYYY-MM-DD HH:MM:SS and time should be formatted in 24-hour format</inlineHelpText>
    <label>Actual Start Date Time</label>
    <length>24</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/ucinn_portal_Volunteer_Shift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <label>Volunteer Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Actual_End_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_End_Date_Time__c</fullName>
    <inlineHelpText>Format as YYYY-MM-DD HH:MM:SS and time should be formatted in 24-hour format</inlineHelpText>
    <label>Actual End Date/Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Actual_Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Actual_Start_Date_Time__c</fullName>
    <inlineHelpText>Format as YYYY-MM-DD HH:MM:SS and time should be formatted in 24-hour format</inlineHelpText>
    <label>Actual Start Date/Time</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <label>Volunteer Job</label>
    <referenceTo>ucinn_portal_Volunteer_Job__c</referenceTo>
    <relationshipLabel>Volunteer Shifts</relationshipLabel>
    <relationshipName>ucinn_portal_Volunteer_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Job__c/Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Governance Campaign</label>
    <nameField>
        <label>Governance Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance Campaign</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_TRIG_VolunteerShiftHandlerTest.cls
@isTest
public without sharing class PORTAL_TRIG_VolunteerShiftHandlerTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public ucinn_portal_Volunteer_Job__c volunteerJob;
        public virtual void setupData() {
            volunteerJob = new ucinn_portal_Volunteer_Job__c(Name = 'Test Job');
            insert volunteerJob;
        }

        public virtual void testRun() {
            setupData();
            List<SObject> newList = new List<SObject>();
            List<SObject> oldList = new List<SObject>();

            ucinn_portal_Volunteer_Shift__c volunteerShift = new ucinn_portal_Volunteer_Shift__c(Name = 'Test Shift', Volunteer_Job__c = volunteerJob.Id, Actual_Start_Date_Time__c = '2022-02-19 12:00:00', Actual_End_Date_Time__c = '2022-02-19 19:00:00');
            newList.add(volunteerShift);
            new PORTAL_TRIG_VolunteerShiftHandler().run(newList, oldList, ucinn_ascendv2.ascend_TDTM_Runnable.Action.BeforeInsert, ucinn_portal_Volunteer_Shift__c.getSObjectType().getDescribe());
            insert volunteerShift;

            ucinn_portal_Volunteer_Shift__c shiftClone = volunteerShift.clone(true, true, false, false);
            shiftClone.Actual_Start_Date_Time__c = null;
            newList = new List<SObject>{shiftClone};
            oldList = new List<SObject>{volunteerShift};

            new PORTAL_TRIG_VolunteerShiftHandler().run(newList, oldList, ucinn_ascendv2.ascend_TDTM_Runnable.Action.BeforeUpdate, ucinn_portal_Volunteer_Shift__c.getSObjectType().getDescribe());
            update shiftClone;
        }
    }
    
    static testMethod void testRun() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_VolunteerShiftHandlerTestClass().testRun();

    }
}