force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/ucinn_ascendv2__Society_Membership__c.object-meta.xml
<CustomObject>
    <description>Constituent or Organization members tied to giving societies.</description>
    <label>Society Membership</label>
    <nameField>
        <label>Society Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Society Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/ucinn_ascendv2__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>ascend Trigger Handler</label>
    <nameField>
        <label>ascend Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ascend Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Class__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Class__c</fullName>
    <description>Name of the class to be run</description>
    <inlineHelpText>Name of the class to be run</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that this module is active</description>
    <inlineHelpText>Indicates that this module is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this module should be run asynchronously in this transaction</description>
    <inlineHelpText>Indicates that this module should be run asynchronously in this transaction</inlineHelpText>
    <label>Is Asynchronous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_User_Managed__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
    <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
    <label>Is User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Load_Order__c</fullName>
    <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
    <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Object__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Object__c</fullName>
    <description>Name of the object this handler should be run for</description>
    <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Trigger_Action__c</fullName>
    <description>Trigger Action in which this module should fire</description>
    <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Event_Waitlist_Entry__c/ucinn_portal_Event_Waitlist_Entry__c.object-meta.xml
<CustomObject>
    <label>Event Waitlist Entry</label>
    <nameField>
        <label>Event Waitlist Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Waitlist Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Job__c/ucinn_portal_Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Listing__c/ucinn_portal_Listing__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Newsletter.recordType-meta.xml
<RecordType>
    <fullName>Newsletter</fullName>
    <active>true</active>
    <label>Newsletter</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Newsletter_Section__c/ucinn_portal_Newsletter_Section__c.object-meta.xml
<CustomObject>
    <label>Newsletter Section</label>
    <nameField>
        <label>Newsletter Section Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Newsletter Sections</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Ticket_Type__c/ucinn_portal_Ticket_Type__c.object-meta.xml
<CustomObject>
    <label>Ticket Type</label>
    <nameField>
        <label>Ticket Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Zone__c/ucinn_portal_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Zone_Membership__c/ucinn_portal_Zone_Membership__c.object-meta.xml
<CustomObject>
    <label>Zone Membership</label>
    <nameField>
        <label>Zone Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zone Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/PORTAL_UTIL_TrigHandlerCreation.cls
/*
 * Copyright (c) 2022, UC Innovation, Inc.  All Rights Reserved.
 *                     https://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */

/**
 * Portal Trigger Handler Creation
 *
 * @author  Phillip Nguyen
 * @since   1.0
 */
public virtual without sharing class PORTAL_UTIL_TrigHandlerCreation {

    public class PortalTriggerHandlerClass {
        public String name;
        public String className;
        public String objectName;
        public String triggerAction;
        public Boolean isActive;
        public Boolean isAsync;
        public Boolean isUserManaged;
        public Integer loadOrder;

        public PortalTriggerHandlerClass(String name, String className, String objectName, String triggerAction) {
            this.name = name;
            this.className = className;
            this.objectName = objectName;
            this.triggerAction = triggerAction;
            this.isActive = true;
            this.isAsync = false;
            this.isUserManaged = false;
            this.loadOrder = 1;
        }
    }

    /**
     * Creates trigger handler classes from a set of mappings
     * 
     * @author  Phillip Nguyen
     * @since   1.0
     * 
     * @return  A list of trigger handler classes
     */
    public static List<PortalTriggerHandlerClass> createTriggerHandlerObjects() {
        List<PortalTriggerHandlerClass> portalTrigHandlerList = new List<PortalTriggerHandlerClass>();
        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Event Waitlist Entry Handler', 
                                                                'PORTAL_TRIG_EventWaitlistEntryHandler',
                                                                'ucinn_portal_Event_Waitlist_Entry__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Ticket Type Handler', 
                                                                'PORTAL_TRIG_TicketTypeHandler',
                                                                'ucinn_portal_Ticket_Type__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Zone Handler', 
                                                                'PORTAL_TRIG_ZoneHandler',
                                                                'ucinn_portal_Zone__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal TRIG Newsletter Section Handler', 
                                                                'PORTAL_TRIG_NewsletterSectionHandler',
                                                                'ucinn_portal_Newsletter_Section__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Zone Membership Handler', 
                                                                'PORTAL_TRIG_ZoneMembershipHandler',
                                                                'ucinn_portal_Zone_Membership__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Job Trigger Handler', 
                                                                'PORTAL_TRIG_JobHandler',
                                                                'ucinn_portal_Job__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Listing Trigger Handler', 
                                                                'PORTAL_TRIG_ListingHandler',
                                                                'ucinn_portal_Listing__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Case Handler', 
                                                                'PORTAL_TRIG_CaseHandler',
                                                                'Case',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Contact Handler', 
                                                                'PORTAL_TRIG_ContactHandler',
                                                                'Contact',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Society Membership Handler', 
                                                                'PORTAL_TRIG_SocietyMembershipHandler',
                                                                'ucinn_ascendv2__Society_Membership__c',
                                                                'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete'));

        portalTrigHandlerList.add(new PortalTriggerHandlerClass('Portal Contact Search Handler', 
                                                                'PORTAL_TRIG_DirectorySearchHandler',
                                                                'Contact',
                                                                'BeforeDelete;AfterInsert;AfterUpdate'));


        return portalTrigHandlerList;                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
    }

    /**
     * Creates Portal ascend Trigger Handlers and inserts them
     * 
     * @author  Phillip Nguyen
     * @since   1.0
     * 
     */
    public static void createPortalTriggerHandlers() {
        List<PortalTriggerHandlerClass> portalTrigHandlerList = createTriggerHandlerObjects();

        if (portalTrigHandlerList == null || portalTrigHandlerList.isEmpty()) {
            return;
        }

        List<ucinn_ascendv2__Trigger_Handler__c> ascendTriggerHandlerListToInsert = new List<ucinn_ascendv2__Trigger_Handler__c>();

        for (PortalTriggerHandlerClass eachPortalTriggerHandler : portalTrigHandlerList) {
            ucinn_ascendv2__Trigger_Handler__c newAscendTriggerHandler = new ucinn_ascendv2__Trigger_Handler__c();
            newAscendTriggerHandler.Name = eachPortalTriggerHandler.name;
            newAscendTriggerHandler.ucinn_ascendv2__Class__c = eachPortalTriggerHandler.className;
            newAscendTriggerHandler.ucinn_ascendv2__Object__c = eachPortalTriggerHandler.objectName;
            newAscendTriggerHandler.ucinn_ascendv2__Trigger_Action__c = eachPortalTriggerHandler.triggerAction;
            newAscendTriggerHandler.ucinn_ascendv2__Is_Active__c = eachPortalTriggerHandler.isActive;
            newAscendTriggerHandler.ucinn_ascendv2__Is_Asynchronous__c = eachPortalTriggerHandler.isAsync;
            newAscendTriggerHandler.ucinn_ascendv2__Is_User_Managed__c = eachPortalTriggerHandler.isUserManaged;
            newAscendTriggerHandler.ucinn_ascendv2__Load_Order__c = eachPortalTriggerHandler.loadOrder;
            
            ascendTriggerHandlerListToInsert.add(newAscendTriggerHandler);
        }

        insert ascendTriggerHandlerListToInsert;
    }
}