force-app/main/default/objects/ucinn_ascendv2__Address_Service_Providers__c/ucinn_ascendv2__Address_Service_Providers__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Address Service Providers</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address_Service_Providers__c/fields/ucinn_ascendv2__Autocomplete_Provider__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Autocomplete_Provider__c</fullName>
    <description>indicate the provider for autocomplete</description>
    <label>Autocomplete Provider</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PORTAL_LWC_AddressServiceHubCtrlTest.cls
@isTest
public with sharing class PORTAL_LWC_AddressServiceHubCtrlTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public virtual void setupData() {
            ucinn_ascendv2__Address_Service_Providers__c provider = new ucinn_ascendv2__Address_Service_Providers__c(
                Name = PORTAL_AddressServiceHubControllerBase.ADDRESS_SERVICE_PROVIDER,
                ucinn_ascendv2__Autocomplete_Provider__c = PORTAL_AddressServiceHubControllerBase.SMARTY_STREETS
            );
            insert provider;
        }

        public virtual void testGetInternationalAutocompleteConfigurationMap() {
            setupData();

            PORTAL_LWC_AddressServiceHubController.SERVER_getInternationalAutocompleteConfigurationMap(null);

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_AddressServiceHubController.SERVER_getInternationalAutocompleteConfigurationMap(null);
                System.assert(false);
            }
            catch (Exception e) { }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_AddressServiceHubController.SERVER_getInternationalAutocompleteConfigurationMap(null);
                System.assert(false);
            }
            catch (Exception e) { }
        }

        public virtual void testGetAutocompleteSuggestions() {
            setupData();

            try {
                PORTAL_LWC_AddressServiceHubController.SERVER_getAutocompleteSuggestions(null);
                System.assert(false);
            }
            catch (Exception e) { }
            
            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_AddressServiceHubController.SERVER_getAutocompleteSuggestions(null);
                System.assert(false);
            }
            catch (Exception e) { }
        }
    }

    @isTest
    public static void testGetInternationalAutocompleteConfigurationMap() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcAddressServiceHubCtrlTestClass().testGetInternationalAutocompleteConfigurationMap();
    }

    @isTest
    public static void testGetAutocompleteSuggestions() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcAddressServiceHubCtrlTestClass().testGetAutocompleteSuggestions();
    }
}