force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/ucinn_ascendv2__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>ascend Trigger Handler</label>
    <nameField>
        <label>ascend Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ascend Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Class__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Class__c</fullName>
    <description>Name of the class to be run</description>
    <inlineHelpText>Name of the class to be run</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that this module is active</description>
    <inlineHelpText>Indicates that this module is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_Asynchronous__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Asynchronous__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that this module should be run asynchronously in this transaction</description>
    <inlineHelpText>Indicates that this module should be run asynchronously in this transaction</inlineHelpText>
    <label>Is Asynchronous</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_User_Managed__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_User_Managed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>The record is managed by the user and updates won&apos;t be pushed to it.</description>
    <inlineHelpText>Check it if you intent to manage the record yourself. Be aware that updates to the package won&apos;t update the record.</inlineHelpText>
    <label>Is User Managed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Load_Order__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Load_Order__c</fullName>
    <description>Order in which this module should be run, helps maintain dependencies in the modules and data.</description>
    <inlineHelpText>Order in which this module should be run, helps maintain dependencies in the modules and data.</inlineHelpText>
    <label>Load Order</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Object__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Object__c</fullName>
    <description>Name of the object this handler should be run for</description>
    <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Trigger_Action__c</fullName>
    <description>Trigger Action in which this module should fire</description>
    <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/ucinn_portal_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Zone__c/fields/Is_Display_on_Portal__c.field-meta.xml
<CustomField>
    <fullName>Is_Display_on_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display on Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/fields/Search_Radius__c.field-meta.xml
<CustomField>
    <fullName>Search_Radius__c</fullName>
    <defaultValue>50</defaultValue>
    <label>Search Radius</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app/main/default/classes/PORTAL_TRIG_ZoneHandlerTest.cls
@isTest
global with sharing class PORTAL_TRIG_ZoneHandlerTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void testUpdateMailingList() {
            ucinn_ascendv2__Trigger_Handler__c zoneHandler = new ucinn_ascendv2__Trigger_Handler__c();
            zoneHandler.Name = 'PORTAL_TRIG_ZoneHandler';
            zoneHandler.ucinn_ascendv2__Class__c = 'PORTAL_TRIG_ZoneHandler';
            zoneHandler.ucinn_ascendv2__Is_Active__c = true;
            zoneHandler.ucinn_ascendv2__Is_Asynchronous__c = false;
            zoneHandler.ucinn_ascendv2__Is_User_Managed__c = false;
            zoneHandler.ucinn_ascendv2__Load_Order__c = 1.0;
            zoneHandler.ucinn_ascendv2__Object__c = 'ucinn_portal_Zone__c';
            zoneHandler.ucinn_ascendv2__Trigger_Action__c = 'BeforeInsert;BeforeUpdate;BeforeDelete;AfterInsert;AfterUpdate;AfterDelete;AfterUndelete';
            zoneHandler = (ucinn_ascendv2__Trigger_Handler__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => zoneHandler});
            insert zoneHandler;

            ucinn_portal_Zone__c zone = new ucinn_portal_Zone__c();
            zone.Is_Display_On_Portal__c = true;
            zone.RecordTypeId = Schema.SObjectType.ucinn_portal_Zone__c.getRecordTypeInfosByDeveloperName().get('Club').getRecordTypeId();
            //not much to validate since it could have different functionality depending on the email api
            zone = (ucinn_portal_Zone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => zone});
            insert zone;
            delete zone;
            undelete zone;
        }

        public virtual void testRun() {
            List<SObject> newList = new List<SObject>();
            List<SObject> oldList = new List<SObject>();

            ucinn_portal_Zone__c zoneRecord = new ucinn_portal_Zone__c(Name = 'Test', City__c = 'Irvine', State__c = 'CA', Country__c = 'USA', Postal_Code__c = '92602', Search_Radius__c = 50);
            newList.add(zoneRecord);
            insert zoneRecord;
            new PORTAL_TRIG_ZoneHandler().run(newList, oldList, ucinn_ascendv2.ascend_TDTM_Runnable.Action.AfterInsert, ucinn_portal_Zone__c.getSObjectType().getDescribe());

            ucinn_portal_Zone__c zoneRecordClone = zoneRecord.clone(true, true, false, false);
            zoneRecordClone.Name = 'Test New';
            newList = new List<SObject>{zoneRecordClone};
            oldList = new List<SObject>{zoneRecord};
            update zoneRecordClone;
            new PORTAL_TRIG_ZoneHandler().run(newList, oldList, ucinn_ascendv2.ascend_TDTM_Runnable.Action.AfterUpdate, ucinn_portal_Zone__c.getSObjectType().getDescribe());
        }
    }

    @isTest
    global static void testUpdateMailingList() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_ZoneHandlerTestClass().testUpdateMailingList();
    }

    @isTest
    global static void testRun() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_ZoneHandlerTestClass().testRun();
    }
}