force-app/main/default/objects/ucinn_portal_Volunteer__c/ucinn_portal_Volunteer__c.object-meta.xml
<CustomObject>
    <label>Volunteer</label>
    <nameField>
        <label>Volunteer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Volunteers</relationshipLabel>
    <relationshipName>ucinn_portal_Volunteers_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <formula>Volunteer_Shift__r.Volunteer_Job__r.Name</formula>
    <label>Volunteer Job</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer__c/fields/Volunteer_Shift__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Shift__c</fullName>
    <label>Volunteer Shift</label>
    <referenceTo>ucinn_portal_Volunteer_Shift__c</referenceTo>
    <relationshipLabel>Volunteers</relationshipLabel>
    <relationshipName>ucinn_portal_Volunteers_Volunteer_Shift</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Job__c/ucinn_portal_Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Volunteer Job</label>
    <nameField>
        <label>Volunteer Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/ucinn_portal_Volunteer_Shift__c.object-meta.xml
<CustomObject>
    <label>Volunteer Shift</label>
    <nameField>
        <label>Volunteer Shift Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Volunteer Shifts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Reminder_Email_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Email_Date_Time__c</fullName>
    <label>Reminder Email Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Reminder_Email_Template__c.field-meta.xml
<CustomField>
    <fullName>Reminder_Email_Template__c</fullName>
    <label>Reminder Email Template</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Volunteer_Shift__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <label>Volunteer Job</label>
    <referenceTo>ucinn_portal_Volunteer_Job__c</referenceTo>
    <relationshipLabel>Volunteer Shifts</relationshipLabel>
    <relationshipName>ucinn_portal_Volunteer_Shifts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Volunteer_Job__c/Volunteer_Job__c.object-meta.xml
<CustomObject>
    <label>Governance Campaign</label>
    <nameField>
        <label>Governance Campaign Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Governance Campaign</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c/Volunteer_Shift__c.object-meta.xml
<CustomObject>
    <label>Committee</label>
    <nameField>
        <label>Committee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Committee</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Volunteer_Shift__c/fields/Volunteer_Job__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Job__c</fullName>
    <label>Governance Campaign</label>
    <referenceTo>Volunteer_Job__c</referenceTo>
    <relationshipLabel>Committees</relationshipLabel>
    <relationshipName>Volunteer_Job_Slots</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/classes/PORTAL_BATCH_VolunteerReminderEmailsTest.cls
@isTest
public class PORTAL_BATCH_VolunteerReminderEmailsTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public Account acc;
        public Contact con;
        public ucinn_portal_Volunteer_Job__c volunteerJobRecord;
        public ucinn_portal_Volunteer_Shift__c volunteerShiftRecord;
        public ucinn_portal_Volunteer__c volunteerRecord;

        private virtual void setupData() {
            volunteerJobRecord = new ucinn_portal_Volunteer_Job__c();

            insert volunteerJobRecord;

            volunteerShiftRecord = new ucinn_portal_Volunteer_Shift__c(Volunteer_Job__c = volunteerJobRecord.Id);
            insert volunteerShiftRecord;

            Account acct = new Account(name = 'ACME Co') ;
            insert acct;

            con = new Contact(LastName = 'Test_Contact',
                              AccountId = acct.Id,
                              Email = 'testCommunityUsermig123@test.com');
            insert con;

            volunteerRecord = new ucinn_portal_Volunteer__c(Volunteer_Shift__c = volunteerShiftRecord.Id, Contact__c = con.Id);
            insert volunteerRecord;
        }

        public virtual void testBatch() {
            setupData();
            Test.startTest();
            Database.executeBatch(new PORTAL_BATCH_VolunteerReminderEmails());
            volunteerJobRecord.Reminder_Email_Date_Time__c = DateTime.now().addHours(-1);
            volunteerJobRecord.Reminder_Email_Template__c = 'Volunteer_Test';
            update volunteerJobRecord;
            Database.executeBatch(new PORTAL_BATCH_VolunteerReminderEmails());
            volunteerShiftRecord.Reminder_Email_Date_Time__c = DateTime.now().addHours(-1);
            volunteerShiftRecord.Reminder_Email_Template__c = 'Volunteer_Test';
            update volunteerShiftRecord;
            Database.executeBatch(new PORTAL_BATCH_VolunteerReminderEmails());
            System.schedule('Hourly', '0 0 * * * ?', new PORTAL_BATCH_VolunteerReminderEmails() );
            Test.stopTest();
        }
    }


    @isTest
    private static void testBatch() {
        PORTAL_TestClassFactory.getTestClassFactory().getVolunteerReminderEmailsTestClass().testBatch();
    }
}