force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/ucinn_ascendv2__Degree_Information__c.object-meta.xml
<CustomObject>
    <description>Degree information of a constituent.</description>
    <label>Degree Information</label>
    <nameField>
        <label>Degree Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Degree Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Degree Information</relationshipLabel>
    <relationshipName>Degree_Information_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Degree_Institution__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Degree_Institution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Degree Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Degree Information</relationshipLabel>
    <relationshipName>Degree_Information_Degree_Institution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_portal_Degree_Institution_Text__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Degree_Institution_Text__c</fullName>
    <label>Degree Institution Text</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/ucinn_ascendv2__Trigger_Handler__c.object-meta.xml
<CustomObject>
    <description>Stores which classes to run in response to DML performed on an object.</description>
    <label>ascend Trigger Handler</label>
    <nameField>
        <label>ascend Trigger Handler Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ascend Trigger Handlers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Class__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Class__c</fullName>
    <description>Name of the class to be run</description>
    <inlineHelpText>Name of the class to be run</inlineHelpText>
    <label>Class</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <description>Indicates that this module is active</description>
    <inlineHelpText>Indicates that this module is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Object__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Object__c</fullName>
    <description>Name of the object this handler should be run for</description>
    <inlineHelpText>Name of the object this handler should be run for</inlineHelpText>
    <label>Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Trigger_Handler__c/fields/ucinn_ascendv2__Trigger_Action__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Trigger_Action__c</fullName>
    <description>Trigger Action in which this module should fire</description>
    <inlineHelpText>Trigger Action in which this module should fire</inlineHelpText>
    <label>Trigger Action</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BeforeInsert</fullName>
            </value>
            <value>
                <fullName>BeforeUpdate</fullName>
            </value>
            <value>
                <fullName>BeforeDelete</fullName>
            </value>
            <value>
                <fullName>AfterInsert</fullName>
            </value>
            <value>
                <fullName>AfterUpdate</fullName>
            </value>
            <value>
                <fullName>AfterDelete</fullName>
            </value>
            <value>
                <fullName>AfterUndelete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PORTAL_TRIG_DegreeInfoHandlerTest.cls
@isTest
public class PORTAL_TRIG_DegreeInfoHandlerTest {
    public virtual class TestClass {
        public virtual void setupTriggerHandler(){
            ucinn_ascendv2__Trigger_Handler__c trigHandler = new ucinn_ascendv2__Trigger_Handler__c(
                Name = 'PORTAL_TRIG_DegreeInfoHandler',
                ucinn_ascendv2__Class__c = 'PORTAL_TRIG_DegreeInfoHandler',
                ucinn_ascendv2__Is_Active__c = true,
                ucinn_ascendv2__Object__c = 'ucinn_ascendv2__Degree_Information__c',
                ucinn_ascendv2__Trigger_Action__c = 'BeforeInsert;BeforeUpdate'
            );
            insert trigHandler;
        }

        public virtual void setupAccount(){
            Account institution = new Account(
                Name = 'UCLA'
            );

            Account dummyInstitution = new Account(
                Name = 'Dummy Employer Organization *DO NOT DELETE*'
            );

            insert new List<Account>{institution, dummyInstitution};
        }

        public virtual void testDegreeInstitutionPopulation() {
            setupTriggerHandler();
            setupAccount();

            Contact testContact = new Contact(
                Lastname = 'Test'
            );
    
            insert testContact;
    
            ucinn_ascendv2__Degree_Information__c degreeInfo = new ucinn_ascendv2__Degree_Information__c(
                ucinn_portal_Degree_Institution_Text__c = 'UCLA',
                Name = 'Test Degree Info',
                ucinn_ascendv2__Contact__c = testContact.Id
            );
    
            insert degreeInfo;
    
            ucinn_ascendv2__Degree_Information__c queriedDegree = [SELECT ID,ucinn_ascendv2__Degree_Institution__c 
                                                                    FROM ucinn_ascendv2__Degree_Information__c WHERE ID =: degreeInfo.Id];
    
    
            System.assertNotEquals(queriedDegree.ucinn_ascendv2__Degree_Institution__c, null, 'Degree Institution should be populated.');
            
            queriedDegree.ucinn_portal_Degree_Institution_Text__c = 'UCSD';
            update queriedDegree;
    
            ucinn_ascendv2__Degree_Information__c updatedDegree = [SELECT ID,ucinn_ascendv2__Degree_Institution__c 
                                                                    FROM ucinn_ascendv2__Degree_Information__c WHERE ID =: degreeInfo.Id];
        }
    }

    static testMethod void testDegreeInstitutionPopulation() {
        PORTAL_TestClassFactory.getTestClassFactory().getTRIG_DegreeInfoHandlerTestClass().testDegreeInstitutionPopulation();
    }
}