force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/ucinn_ascendv2__Address_Relation__c.object-meta.xml
<CustomObject>
    <description>Junction object to associate addresses with constituent or organization.</description>
    <label>Address Relation</label>
    <nameField>
        <label>Address Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Address Relations</relationshipLabel>
    <relationshipName>Address_Relations_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Address Removed</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Foreign-Verified</fullName>
                <isActive>false</isActive>
                <label>Foreign-Verified</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <isActive>false</isActive>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Lost Address</fullName>
                <isActive>false</isActive>
                <label>Lost Address</label>
            </value>
            <value>
                <fullName>NCOA Address</fullName>
                <isActive>false</isActive>
                <label>NCOA Address</label>
            </value>
            <value>
                <fullName>Not found-Indv Address Search</fullName>
                <isActive>false</isActive>
                <label>Not found-Indv Address Search</label>
            </value>
            <value>
                <fullName>Parent Address</fullName>
                <isActive>false</isActive>
                <label>Parent Address</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/ucinn_ascendv2__Degree_Information__c.object-meta.xml
<CustomObject>
    <description>Degree information of a constituent.</description>
    <label>Degree Information</label>
    <nameField>
        <label>Degree Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Degree Information</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Conferred_Degree_Year__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Conferred_Degree_Year__c</fullName>
    <label>Conferred Degree Year</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Degree Information</relationshipLabel>
    <relationshipName>Degree_Information_Contact</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Degree__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Degree__c</fullName>
    <label>Degree</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>BS</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MBA</fullName>
            </value>
            <value>
                <fullName>MFA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>JD</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Undergraduate</fullName>
            </value>
            <value>
                <fullName>Graduate</fullName>
            </value>
            <value>
                <fullName>LLM</fullName>
            </value>
            <value>
                <fullName>LLB</fullName>
            </value>
            <value>
                <fullName>Asc</fullName>
            </value>
            <value>
                <fullName>Cert</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Degree_Institution__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Degree_Institution__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Degree Institution</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Degree Information</relationshipLabel>
    <relationshipName>Degree_Information_Degree_Institution</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_ascendv2__Interim__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Interim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interim</label>
    <referenceTo>ucinn_ascendv2__Interim__c</referenceTo>
    <relationshipLabel>Degree Information</relationshipLabel>
    <relationshipName>Degree_Information_Interim</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Degree_Information__c/fields/ucinn_portal_Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/ucinn_ascendv2__Email__c.object-meta.xml
<CustomObject>
    <description>The emails of the constituent.</description>
    <label>Email</label>
    <nameField>
        <label>Email Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Emails</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Emails</relationshipLabel>
    <relationshipName>Emails_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Email_Address__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Email_Address__c</fullName>
    <label>Email Address</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Email__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/ucinn_ascendv2__Interim__c.object-meta.xml
<CustomObject>
    <description>The shell object used for Integration that stores the fields for constituents.</description>
    <label>Interim</label>
    <nameField>
        <label>Interim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contact ID that matches this Interim__C object</description>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Interims</relationshipLabel>
    <relationshipName>Interims_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Supervisor Review</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Do Not Process</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/recordTypes/Bio_Information_Self_Report.recordType-meta.xml
<RecordType>
    <fullName>Bio_Information_Self_Report</fullName>
    <active>true</active>
    <label>Bio Information Self Report</label>
</RecordType>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/ucinn_ascendv2__Org_Wide_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Org Wide Configuration</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status addresses of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Addresses Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Emails_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Emails_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status emails of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Emails Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status phones of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Phones Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/ucinn_ascendv2__Phone__c.object-meta.xml
<CustomObject>
    <description>The phone numbers of the constituent or organization.</description>
    <label>Phone</label>
    <nameField>
        <label>Phone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Phones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Phones</relationshipLabel>
    <relationshipName>Phones_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Phone__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Current</fullName>
                <default>true</default>
                <label>Current</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator_Value__c/ucinn_ascendv2__Service_Indicator_Value__c.object-meta.xml
<CustomObject>
    <description>List of preferences that a constituent may have, such as Do Not Call, Do Not Solicit, etc.</description>
    <label>Service Indicator Value</label>
    <nameField>
        <label>Service Indicator Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Indicator Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator_Value__c/fields/ucinn_portal_Is_Display_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Is_Display_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PORTAL_MyInformationEditCtrlBaseTest.cls
@isTest
public with sharing class PORTAL_MyInformationEditCtrlBaseTest {
    public virtual class TestClass extends PORTAL_TestClassBase {
        public Contact con;
        public User communityUser;
        public ucinn_ascendv2__Degree_Information__c schoolDegree;
        public ucinn_ascendv2__Interim__c selfReportInterim;
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void setupData(){
            System.runAs(thisUser) {
                ucinn_ascendv2__Org_Wide_Configuration__c orgSettings = new ucinn_ascendv2__Org_Wide_Configuration__c();
                orgSettings.Name = 'Default Org Wide Config';
                orgSettings.ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c = true;
                orgSettings.ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c = true;
                orgSettings.ucinn_ascendv2__Is_Multiple_Current_Emails_Enabled__c = true;
                orgSettings = (ucinn_ascendv2__Org_Wide_Configuration__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => orgSettings});
                insert orgSettings;

                Id profileId = [SELECT Id FROM Profile WHERE Name = :'ascend Customer Community User'].Id;
                Account acct = new Account(name = 'ACME Co') ;
                acct = (Account)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => acct});
                insert acct;

                Contact dummyContact = new Contact();
                dummyContact.FirstName = 'My Information Dummy Contact';
                dummyContact.LastName = 'Do Not Delete This Record';
                dummyContact.AccountId = acct.Id;
                dummyContact = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => dummyContact});
                insert dummyContact;

                con = new Contact(LastName = 'Test_Contact',
                                AccountId = acct.Id,
                                ucinn_portal_Is_Display_On_Portal__c = true,
                                Email = 'testCommunityUsermig123@test.com');

                con = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => con});
                insert con;

                communityUser = new User(alias = 'comUser',
                                        email = 'testCommunityUsermig123@test.com',
                                        emailencodingkey='UTF-8',
                                        lastname = 'Batman',
                                        languagelocalekey='en_US',
                                        localesidkey='en_US',
                                        profileid = profileId,
                                        IsActive = true,
                                        ContactId = con.Id,
                                        timezonesidkey='America/Los_Angeles',
                                        username = System.now().millisecond() + 'testCommunityUsermig123@test.com');

                communityUser = (User)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => communityUser});
                insert communityUser;

                ucinn_ascendv2__Email__c email = new ucinn_ascendv2__Email__c();
                email.ucinn_ascendv2__Contact__c = con.Id;
                email.ucinn_ascendv2__Email_Address__c = 'blahblah@test.com';
                email.ucinn_ascendv2__Status__c = 'Current';
                email.ucinn_portal_Is_Display_On_Portal__c = true;
                email = (ucinn_ascendv2__Email__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => email});
                insert email;

                schoolDegree = new ucinn_ascendv2__Degree_Information__c(
                    ucinn_ascendv2__Contact__c = con.Id,
                    ucinn_ascendv2__Degree_Institution__c = acct.Id, 
                    ucinn_ascendv2__Degree__c = 'BS',
                    ucinn_ascendv2__Conferred_Degree_Year__c = '2018',
                    ucinn_portal_Is_Display_On_Portal__c = true,
                    ucinn_portal_Status__c = 'Active',
                    recordTypeId = Schema.SObjectType.ucinn_ascendv2__Degree_Information__c.getRecordTypeInfosByDeveloperName().get('School_Degree_Information').getRecordTypeId()
                );
                insert schoolDegree;

                selfReportInterim = new ucinn_ascendv2__Interim__c(
                    ucinn_ascendv2__Contact__c = con.Id, 
                    ucinn_ascendv2__Status__c = PORTAL_MyInformationEditControllerBase.MANUAL_REVIEW,
                    recordTypeId = Schema.SObjectType.ucinn_ascendv2__Interim__c.getRecordTypeInfosByDeveloperName().get(PORTAL_MyInformationEditControllerBase.BIO_INFORMATION_SELF_REPORT).getRecordTypeId(),
                    ucinn_ascendv2__Birthdate__c = Date.newInstance(2000, 12, 31)
                );

                insert selfReportInterim;

                ucinn_ascendv2__Service_Indicator_Value__c serviceIndicatorValue = new ucinn_ascendv2__Service_Indicator_Value__c();
                serviceIndicatorValue.Name = 'Test';
                serviceIndicatorValue.ucinn_portal_Portal_Description__c = 'Test Service Indicator';
                serviceIndicatorValue = (ucinn_ascendv2__Service_Indicator_Value__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => serviceIndicatorValue});
                insert serviceIndicatorValue;
            }
        }

        public virtual void testSaveEmail() {
            Test.startTest();
            setupData();
            List<Map<String,Object>> records = new List<Map<String,Object>>();
            records.add(new Map<String, Object>{'emailAddress' => 'testmyinfomail@test.com', 'emailType' => 'Personal', 'isDelete' => false});

            Map<Object, Object> params = new Map<Object, Object>();
            params.put('emails', records);
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());

            System.runAs(communityUser) {
                controller.saveInformation(new Map<String, Object>{'sectionIdToUpdatedRecordsMap' => params});
                List<ucinn_ascendv2__Email__c> emailList = [SELECT Id, ucinn_ascendv2__Type__c FROM ucinn_ascendv2__Email__c];
                Assert.areEqual(1, emailList.size());

                records = new List<Map<String,Object>>();
                records.add(new Map<String, Object>{'emailAddress' => 'testmyinfomail1234@test.com', 'emailType' => 'Personal', 'isDelete' => false, 'Id' => emailList.get(0).Id});

                params = new Map<Object, Object>();
                params.put('emails', records);
                controller.saveInformation(new Map<String, Object>{'sectionIdToUpdatedRecordsMap' => params});
                emailList = [SELECT Id, ucinn_ascendv2__Type__c FROM ucinn_ascendv2__Email__c];
                Assert.areEqual(2, emailList.size());
            }

            Test.stopTest();
        }

        public virtual void testSavePhone() {
            Test.startTest();
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
    
            List<Map<String,Object>> records = new List<Map<String,Object>>();
            records.add(new Map<String, Object>{'phoneNumber' => '9991231234', 'phoneType' => 'Other', 'isDelete' => false});

            Map<Object, Object> params = new Map<Object, Object>();
            params.put('phones', records);

            System.runAs(communityUser) {
                controller.saveInformation(new Map<String, Object>{'sectionIdToUpdatedRecordsMap' => params});
                List<ucinn_ascendv2__Phone__c> phoneList = [SELECT Id FROM ucinn_ascendv2__Phone__c WHERE ucinn_ascendv2__Contact__c =: con.Id];
                Assert.areEqual(1, phoneList.size());

                // delete
                records = new List<Map<String,Object>>();
                records.add(new Map<String, Object>{'phoneNumber' => '9991231234', 'phoneType' => 'Other', 'isDelete' => true, 'Id' => phoneList.get(0).Id});

                params = new Map<Object, Object>();
                params.put('phones', records);

                controller.saveInformation(new Map<String, Object>{'sectionIdToUpdatedRecordsMap' => params});
                phoneList = [SELECT Id, ucinn_ascendv2__Status__c FROM ucinn_ascendv2__Phone__c WHERE ucinn_ascendv2__Contact__c =: con.Id AND ucinn_ascendv2__Phone_Number__c = '9991231234'];
                Assert.areEqual('Former', phoneList.get(0).ucinn_ascendv2__Status__c);
            }
            Test.stopTest();
        }

        public virtual void testSaveAddress() {
            Test.startTest();
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
    
            List<Map<String,Object>> records = new List<Map<String,Object>>();
            records.add(new Map<String, Object>{'addressLine1' => 'Test Addy', 'addressCity' => 'Irvine', 'addressType' => 'Other', 'isDelete' => false});

            Map<Object, Object> params = new Map<Object, Object>();
            params.put('addresses', records);

            System.runAs(communityUser) {
                controller.saveInformation(new Map<String, Object>{'sectionIdToUpdatedRecordsMap' => params});
                List<ucinn_ascendv2__Address_Relation__c> addressRelationList = [SELECT Id FROM ucinn_ascendv2__Address_Relation__c];
                Assert.areEqual(1, addressRelationList.size());
            }
            Test.stopTest();
        }

        public virtual void testSavePersonalInformation() {
            Test.startTest();
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
    
            List<Map<String,Object>> nameRecords = new List<Map<String,Object>>();
            nameRecords.add(new Map<String, Object>{'firstName' => 'FirstNameTest', 'isDelete' => false});

            Map<Object, Object> params = new Map<Object, Object>();
            params.put('name', nameRecords);

            List<Map<String,Object>> additionalDetailsRecords = new List<Map<String, Object>>();
            additionalDetailsRecords.add(new Map<String, Object>{'spouseFirstName' => 'SpouseFirstNameTest', 
                                                                'gender' => 'Female',
                                                                'isDelete' => false});
            params.put('additionalDetails', additionalDetailsRecords);

            List<Map<String,Object>> directoryRecords = new List<Map<String, Object>>();
            directoryRecords.add(new Map<String, Object>{'directoryFirstName' => 'TonyDirName', 'isDelete' => false});
            params.put('directoryName', directoryRecords);

            System.runAs(communityUser) {
                controller.saveInformation(new Map<String, Object>{'sectionIdToUpdatedRecordsMap' => params});
                List<Contact> contactList = [SELECT Id FROM Contact WHERE Email = 'testCommunityUsermig123@test.com' AND ucinn_ascendv2__Gender__c = 'Female'];
                Assert.areEqual(1, contactList.size());

                List<ucinn_ascendv2__Interim__c> interimList = [SELECT Id FROM ucinn_ascendv2__Interim__c WHERE ucinn_ascendv2__First_Name__c = 'FirstNameTest' AND ucinn_portal_Directory_First_Name__c = 'TonyDirName'];
                Assert.areEqual(1, interimList.size());
            }
            Test.stopTest();
        }

        public virtual void testGetEditInfo() {
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
            // testing section with birthdate since Self Report page section settings exist from v1 and work with v2
            Map<String, Object> params = new Map<String, Object>{
                PORTAL_MyInformationEditControllerBase.PAGE_NAME => 'My Information',
                PORTAL_MyInformationEditControllerBase.MAIN_SECTION_NAME => 'Personal_Information',
                PORTAL_MyInformationEditControllerBase.SUB_SECTION_NAME => 'Additional_Details',
                PORTAL_MyInformationEditControllerBase.SELF_REPORT_PAGE_NAME => 'My Information Self Report'
            };

            Test.startTest();
            System.runAs(communityUser) {
                Map<String, Object> responseMap = controller.getEditInfo(params);
                PORTAL_MyInfoRetriever.MyInfoConfiguration configuration = (PORTAL_MyInfoRetriever.MyInfoConfiguration)JSON.deserialize((String)responseMap.get(PORTAL_MyInfoRetriever.CONFIG_STRING), PORTAL_MyInfoRetriever.MyInfoConfiguration.class);

                System.assert(configuration.sectionConfigurationMap.containsKey('additionalDetails'));
                System.assert(configuration.selfReportSectionConfigurationMap.containsKey('additionalDetails'));
                System.assertEquals(1, ((List<Object>)responseMap.get(PORTAL_MyInfoRetriever.RECORD_LIST_WITH_STAGED_CHANGES)).size());
                System.assertEquals(1, ((List<Object>)responseMap.get(PORTAL_MyInfoRetriever.SELF_REPORT_RECORD_LIST)).size());
            }
            Test.stopTest();
        }

        public virtual void testSelfReportBirthdate() {
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
            
            // testing section with birthdate since Self Report page section settings exist from v1 and work with v2
            Map<String, Object> birthdateMap = new Map<String, Object>{
                'Id' => selfReportInterim.Id, // not strictly necessary, but this emulates frontend more closely 
                'birthdate' => '2000-10-31',
                'isBirthdateDeleted' => false
            };
            
            Map<String, Object> params = new Map<String, Object>{
                PORTAL_MyInformationEditControllerBase.SELF_REPORT_RECORD_MAP => birthdateMap,
                PORTAL_MyInformationEditControllerBase.PAGE_NAME => 'My Information Self Report',
                PORTAL_MyInformationEditControllerBase.MAIN_SECTION_NAME => 'Personal_Information',
                PORTAL_MyInformationEditControllerBase.SUB_SECTION_NAME => 'Additional_Details',
                PORTAL_MyInformationEditControllerBase.SECTION_ID => 'additionalDetails'
            };

            Test.startTest();
            System.runAs(communityUser) {
                Map<String, Object> result = controller.selfReportInformation(params);
                System.assertEquals(selfReportInterim.Id, (String)result.get('Id'));
                System.assertEquals(Date.newInstance(2000, 10, 31), (Date)result.get('birthdate'));

                // test self report when the self report interim is not created yet
                String previousId = selfReportInterim.Id;
                delete selfReportInterim;
                birthdateMap.remove('Id');

                result = controller.selfReportInformation(params);
                System.assertNotEquals(previousId, (String)result.get('Id'));
                System.assertEquals(Date.newInstance(2000, 10, 31), (Date)result.get('birthdate'));
            }

            Test.stopTest();
        }

        public virtual void testSelfReportSchoolDegree() {
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
            
            // Self Report page section settings for School Degrees exists in v1, so this test still works for v2 
            // There are some page section setting fields missing that v2 uses, but the code still runs to completion
            Map<String, Object> degreeRecordMap = new Map<String, Object>{
                'masterDegree' => schoolDegree.Id, // not strictly necessary, but this emulates frontend more closely  
                'schoolDegreeDegree' => 'MS',
                'schoolDegreeYear' => '2019',
                'postCode' => null,
                'minorCode' => null
            };
            
            Map<String, Object> params = new Map<String, Object>{
                PORTAL_MyInformationEditControllerBase.SELF_REPORT_RECORD_MAP => degreeRecordMap,
                PORTAL_MyInformationEditControllerBase.PAGE_NAME => 'My Information Self Report',
                PORTAL_MyInformationEditControllerBase.MAIN_SECTION_NAME => 'Degrees',
                PORTAL_MyInformationEditControllerBase.SUB_SECTION_NAME => 'School_Degree_Information',
                PORTAL_MyInformationEditControllerBase.SECTION_ID => 'schoolDegreesSelfReport',
                PORTAL_MyInformationEditControllerBase.ORIGINAL_RECORD_ID => schoolDegree.Id // doesn't do anything if the page section setting's Original Record Field API Name is blank
            };

            Test.startTest();
            System.runAs(communityUser) {
                Map<String, Object> result = controller.selfReportInformation(params);
                System.assertNotEquals(schoolDegree.Id, (String)result.get('Id'));
                System.assertEquals('MS', (String)result.get('schoolDegreeDegree'));
                System.assertEquals('2019', (String)result.get('schoolDegreeYear'));
            }
            Test.stopTest();
        }

        public virtual void testSearchServiceIndicatorValues() {
            Test.startTest();
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
            Map<String, Object> params = new Map<String, Object>{
                PORTAL_MyInformationEditControllerBase.SEARCH_TEXT => 'Test',
                PORTAL_MyInformationEditControllerBase.PAGE_NAME => 'My Information',
                PORTAL_MyInformationEditControllerBase.MAIN_SECTION_NAME => 'Privacy_Settings',
                PORTAL_MyInformationEditControllerBase.SUB_SECTION_NAME => 'Service Indicator Values',
                PORTAL_MyInformationEditControllerBase.SECTION_ID => 'serviceIndicatorValues'
            };

            System.runAs(communityUser) {
                List<Map<String, Object>> result = controller.searchServiceIndicatorValues(params);
            }
            Test.stopTest();
        }

        public virtual void testIsDisplaySearchBar() {
            Test.startTest();
            setupData();
            PORTAL_MyInformationEditControllerBase controller = ((PORTAL_MyInformationEditControllerBase)PORTAL_Utils.getControllerFactory().getMyInformationv2EditController());
            Boolean result = controller.isDisplaySearchBar(new Map<String, Object>());
            Assert.areEqual(true, result);
            Test.stopTest();
        }
    }
    
    @isTest
    public static void testSaveEmail() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSaveEmail();
    }

    @isTest
    public static void testSavePhone() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSavePhone();
    }

    @isTest
    public static void testSaveAddress() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSaveAddress();
    }

    @isTest
    public static void testSavePersonalInformation() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSavePersonalInformation();
    }

    /**
     * Test getEditInfo for my info v2
     * @author Jacob Huang
     * @since 1.10
     */
    @isTest
    public static void testGetEditInfo() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testGetEditInfo();
    }

    /**
     * Test selfReportInformation for my info v2 with birthdate
     * @author Jacob Huang
     * @since 1.10
     */
    @isTest
    public static void testSelfReportBirthdate() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSelfReportBirthdate();
    }

    /**
     * Test selfReportInformation for my info v2 with a school degree information
     * @author Jacob Huang
     * @since 1.10
     */
    @isTest
    public static void testSelfReportSchoolDegree() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSelfReportSchoolDegree();
    }

    /**
     * Test searching for service indicator value
     * @author Phillip Nguyen
     * @since 1.12
     */
    @isTest
    public static void testSearchServiceIndicatorValues() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testSearchServiceIndicatorValues();
    }

    /**
     * Test if we display search bar
     * @author Phillip Nguyen
     * @since 1.12
     */
    @isTest
    public static void testIsDisplaySearchBar() {
        PORTAL_TestClassFactory.getTestClassFactory().getMyInformationEditCtrlBaseTestClass().testIsDisplaySearchBar();
    }
}