force-app/main/default/objects/ucinn_portal_Event_Waitlist_Entry__c/ucinn_portal_Event_Waitlist_Entry__c.object-meta.xml
<CustomObject>
    <label>Event Waitlist Entry</label>
    <nameField>
        <label>Event Waitlist Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Event Waitlist Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Event_Waitlist_Entry__c/fields/Expiration_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date_Time__c</fullName>
    <label>Expiration Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Event_Waitlist_Entry__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <formula>Ticket_Type__r.Listing__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Listing</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Event_Waitlist_Entry__c/fields/Ticket_Type__c.field-meta.xml
<CustomField>
    <fullName>Ticket_Type__c</fullName>
    <label>Ticket Type</label>
    <referenceTo>ucinn_portal_Ticket_Type__c</referenceTo>
    <relationshipLabel>Event Waitlist Entries</relationshipLabel>
    <relationshipName>ucinn_portal_Event_Waitlist_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/ucinn_portal_Listing__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Start_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_Time__c</fullName>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Ticket_Type__c/ucinn_portal_Ticket_Type__c.object-meta.xml
<CustomObject>
    <label>Ticket Type</label>
    <nameField>
        <label>Ticket Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Ticket Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Ticket_Type__c/fields/Listing__c.field-meta.xml
<CustomField>
    <fullName>Listing__c</fullName>
    <label>Listing</label>
    <referenceTo>ucinn_portal_Listing__c</referenceTo>
    <relationshipLabel>Ticket Types</relationshipLabel>
    <relationshipName>ucinn_portal_Ticket_Types_Listing</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PORTAL_BATCH_EventWaitlistDeletionTest.cls
@isTest
public without sharing class PORTAL_BATCH_EventWaitlistDeletionTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void testBatch() {
            ucinn_portal_Listing__c listing = new ucinn_portal_Listing__c();
            listing.Name = 'Test Event';
            listing.RecordTypeId = Schema.SObjectType.ucinn_portal_Listing__c.getRecordTypeInfosByDeveloperName().get(PORTAL_CONST_Listing.EVENT).getRecordTypeId();
            listing.Start_Date_Time__c = Datetime.now().addDays(-30);
            listing = (ucinn_portal_Listing__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => listing});
            insert listing;

            ucinn_portal_Ticket_Type__c ticketType = new ucinn_portal_Ticket_Type__c(Listing__c = listing.Id, Name = 'Test');
            ticketType = (ucinn_portal_Ticket_Type__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => ticketType});
            insert ticketType;

            ucinn_portal_Event_Waitlist_Entry__c waitlistEntry = new ucinn_portal_Event_Waitlist_Entry__c(Ticket_Type__c = ticketType.Id, First_Name__c = 'Test', Last_Name__c = 'Test', Email__c = 'test@test.com', Expiration_Date_Time__c = DateTime.now().addMinutes(-5));
            waitlistEntry = (ucinn_portal_Event_Waitlist_Entry__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => waitlistEntry});
            insert waitlistEntry;

            Test.startTest();
            Database.executeBatch(new PORTAL_BATCH_EventWaitlistDeletion());
            Test.stopTest();
        }

        public virtual void testScheduler() {
            Test.startTest();
            String chron = '0 0 23 * * ?';
            System.schedule('Test Sched', chron, new PORTAL_BATCH_EventWaitlistDeletion());
            Test.stopTest();

        }
    }
    @IsTest
    public static void testBatch() {
        PORTAL_TestClassFactory.getTestClassFactory().getEventWaitlistDeletionTestClass().testBatch();
    }

    @IsTest
    public static void testScheduler() {
        PORTAL_TestClassFactory.getTestClassFactory().getEventWaitlistDeletionTestClass().testScheduler();
    }
}