force-app/main/default/objects/ucinn_ascendv2__Designation__c/ucinn_ascendv2__Designation__c.object-meta.xml
<CustomObject>
    <description>The department/unit/fund where the donation will be going to.</description>
    <label>Designation</label>
    <nameField>
        <label>Designation Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Designation__c/fields/ucinn_ascendv2__Designation_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation_Name__c</fullName>
    <inlineHelpText>Displayed on Gift Processing and Giving Detail</inlineHelpText>
    <label>Designation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Designation__c/fields/ucinn_portal_Is_Display_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Is_Display_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Giving_Society__c/ucinn_ascendv2__Giving_Society__c.object-meta.xml
<CustomObject>
    <description>Memberships to schools and university wide associations that makes charitable donations/gifts back to their donors using rule sets to determine the level of charitable acts.</description>
    <label>Giving Society</label>
    <nameField>
        <label>Giving Society Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Giving Societies</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Giving_Society__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Historied</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Giving_Society__c/fields/ucinn_portal_Is_Display_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Is_Display_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Giving_Society__c/fields/ucinn_portal_Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Annual</fullName>
            </value>
            <value>
                <fullName>Lifetime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Level_Benefit__c/ucinn_ascendv2__Level_Benefit__c.object-meta.xml
<CustomObject>
    <description>Junction object between Membership Benefit and Levels</description>
    <label>Level / Benefit</label>
    <nameField>
        <label>Level/Benefit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Levels / Benefits</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Level_Benefit__c/fields/ucinn_ascendv2__Membership_Benefit_Product__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Membership_Benefit_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Benefit</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Levels / Benefits</relationshipLabel>
    <relationshipName>Levels_Benefits_Membership_Benefit_Prod</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Level_Benefit__c/fields/ucinn_ascendv2__Membership_Level_Product__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Membership_Level_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Level</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Levels / Benefits (Membership Level)</relationshipLabel>
    <relationshipName>Levels_Benefits_Membership_Level_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/ucinn_ascendv2__Society_Membership__c.object-meta.xml
<CustomObject>
    <description>Constituent or Organization members tied to giving societies.</description>
    <label>Society Membership</label>
    <nameField>
        <label>Society Membership Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Society Memberships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Society Memberships</relationshipLabel>
    <relationshipName>Society_Memberships_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/fields/ucinn_ascendv2__Giving_Society__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Giving_Society__c</fullName>
    <label>Giving Society</label>
    <referenceTo>ucinn_ascendv2__Giving_Society__c</referenceTo>
    <relationshipLabel>Society Memberships</relationshipLabel>
    <relationshipName>Society_Memberships_Giving_Society</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/fields/ucinn_ascendv2__Member_Since__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Member_Since__c</fullName>
    <description>First time member joined the society</description>
    <label>Member Since</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/fields/ucinn_ascendv2__Membership_Level_Product__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Membership_Level_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Membership Level</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Society Memberships</relationshipLabel>
    <relationshipName>Society_Memberships_Membership_Lev_Prod</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/fields/ucinn_portal_Is_Renewal_Solicit_Opt_Out__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Is_Renewal_Solicit_Opt_Out__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Renewal Solicit Opt Out</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Society_Membership__c/fields/ucinn_portal_Is_Show_on_Honor_Roll__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Is_Show_on_Honor_Roll__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Show on Honor Roll</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PORTAL_MembershipControllerTest.cls
@isTest
public without sharing class PORTAL_MembershipControllerTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public Contact contactRecord;
        public ucinn_ascendv2__Society_Membership__c societyMembership;
        public User contactUser;
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void setUpContacts() {
            System.runAs(thisUser) {
                Account account = new Account(name = 'Test Account');
                account = (Account)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => account});
                insert account;

                contactRecord = new Contact(LastName = 'Test Contact',
                                            AccountId = account.Id,
                                            ucinn_portal_Honor_Roll_Joint_Preference__c = 'Individual',
                                            ucinn_portal_Is_Honor_Roll_Opt_Out__c = false,
                                            ucinn_portal_Is_Renewal_Solicit_Opt_Out__c = false);

                contactRecord = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => contactRecord});
                insert contactRecord;

                Id profileId = [select id from profile where name=: 'ascend Customer Community User'].id;
                User newUser = new User(ContactId = contactRecord.Id,
                                        ProfileId = profileId,
                                        Username = System.now().millisecond() + 'testuser@test.com',
                                        Alias = 'testers',
                                        Email='testuser1@test.com',
                                        EmailEncodingKey='UTF-8',
                                        Firstname='Test',
                                        Lastname='User',
                                        LanguageLocaleKey='en_US',
                                        LocaleSidKey='en_US',
                                        TimeZoneSidKey='America/Chicago');

                newUser = (User)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => newUser});
                insert newUser;

                contactUser = newUser;
            }
        }

        public virtual void setUpSocietyMemberships() {
            if (contactRecord == null) {
                setUpContacts();
            }

            Period fiscalYearInfo = PORTAL_CommunityUtils.getCurrentFiscalYear(null);

            ucinn_ascendv2__Giving_Society__c givingSociety = new ucinn_ascendv2__Giving_Society__c(Name = 'Test Giving Society',
                                                                                                    ucinn_ascendv2__Status__c = 'Active',
                                                                                                    ucinn_portal_Is_Display_On_Portal__c = true,
                                                                                                    ucinn_portal_Type__c = 'Annual');

            givingSociety = (ucinn_ascendv2__Giving_Society__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => givingSociety});
            insert givingSociety;

            ucinn_ascendv2__Designation__c designation = new ucinn_ascendv2__Designation__c(
                Name = 'Athletics',
                ucinn_ascendv2__Designation_Name__c  = 'Athletics',
                ucinn_portal_Is_Display_On_Portal__c = true
            );

            Product2 membershipLevel = new Product2(ucinn_ascendv2__Giving_Society__c = givingSociety.Id,
                                                    ucinn_ascendv2__Months_Allocated_on_Payment__c = 12,
                                                    ucinn_ascendv2__Payment_Options__c = 'One-Time Membership',
                                                    Name = 'Test',
                                                    ucinn_ascendv2__Designation__c = designation.Id);

            membershipLevel = (Product2)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => membershipLevel});
            insert membershipLevel;

            societyMembership = new ucinn_ascendv2__Society_Membership__c(Name = 'Test Membership',
                                                                          ucinn_ascendv2__Membership_Level_Product__c = membershipLevel.Id,
                                                                          ucinn_ascendv2__Giving_Society__c = givingSociety.Id,
                                                                          ucinn_ascendv2__Contact__c = contactRecord.Id,
                                                                          ucinn_ascendv2__Member_Since__c = fiscalYearInfo.StartDate,
                                                                          ucinn_portal_Is_Show_on_Honor_Roll__c = true,
                                                                          ucinn_portal_Is_Display_On_Portal__c = true,
                                                                          ucinn_portal_Is_Renewal_Solicit_Opt_Out__c = false);

            societyMembership = (ucinn_ascendv2__Society_Membership__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => societyMembership});
            insert societyMembership;
        }

        public virtual void setUpBenefits() {
            if (societyMembership == null) {
                setUpSocietyMemberships();
            }

            String benefitId = Schema.SObjectType.Product2.getRecordTypeInfosByDeveloperName().get('Membership_Benefit').getRecordTypeId();

            Product2 benefitProduct = new Product2(Description = 'Benefit Description',
                                                    Name = 'Test Benefit',
                                                    RecordTypeId = benefitId);

            benefitProduct = (Product2)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => benefitProduct});
            insert benefitProduct;

            ucinn_ascendv2__Level_Benefit__c junctionBenefit = new ucinn_ascendv2__Level_Benefit__c(ucinn_ascendv2__Membership_Benefit_Product__c = benefitProduct.Id, 
                                                                                                    ucinn_ascendv2__Membership_Level_Product__c = societyMembership.ucinn_ascendv2__Membership_Level_Product__c);
            
            junctionBenefit = (ucinn_ascendv2__Level_Benefit__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => junctionBenefit});
            insert junctionBenefit;

            PricebookEntry pricebookEntry = new PricebookEntry(Product2Id = benefitProduct.Id, Pricebook2Id = Test.getStandardPricebookId(), UnitPrice = 50);
            pricebookEntry = (PricebookEntry)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => pricebookEntry});
            insert pricebookEntry;
        }

        public virtual void testinitializeMembershipPurchase() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();

            controller.initializeMembershipPurchase(null);

            controller.initializeMembershipPurchase(new Map<String, Object>{'test' => 'test'});

            controller.initializeMembershipPurchase(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'test',
                                                                            PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'test'});

            controller.initializeMembershipPurchase(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'Membership Purchase',
                                                                            PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'Membership Purchase'});

            controller.initializeMembershipPurchase(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'Membership Purchase',
                                                                            PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'Membership Purchase',
                                                                            PORTAL_MembershipControllerBase.PAYMENT_METHOD => 'TouchNet'});

            setUpContacts();

            setUpSocietyMemberships();

            System.runAs(contactUser){
                controller.initializeMembershipPurchase(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'Membership Purchase',
                                                                                PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'Membership Purchase',
                                                                                PORTAL_MembershipControllerBase.MEMBERSHIP_RECORD_ID => societyMembership.Id});

                controller.initializeMembershipPurchase(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'Membership Purchase',
                                                                                PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'Membership Purchase',
                                                                                PORTAL_MembershipControllerBase.MEMBERSHIP_RECORD_ID => societyMembership.Id,
                                                                                PORTAL_MembershipControllerBase.PAYMENT_METHOD => 'TouchNet'});
            }
        }

        public virtual void testGetMembershipFieldsToPrepopulate() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();

            setUpContacts();
            setUpSocietyMemberships();

            controller.getMembershipFieldsToPrepopulate(null);

            controller.getMembershipFieldsToPrepopulate(new Map<String, Object>{'test' => 'test'});

            controller.getMembershipFieldsToPrepopulate(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'test',
                                                                                PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'test',
                                                                                PORTAL_MembershipControllerBase.SUB_SECTION_NAME => 'test',
                                                                                PORTAL_MembershipControllerBase.MEMBERSHIP_LEVEL_ID => societyMembership.ucinn_ascendv2__Membership_Level_Product__c});
            System.runAs(contactUser){
                controller.getMembershipFieldsToPrepopulate(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'Membership Purchase',
                                                                                PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'Membership Purchase',
                                                                                PORTAL_MembershipControllerBase.SUB_SECTION_NAME => 'One Time Membership',
                                                                                PORTAL_MembershipControllerBase.MEMBERSHIP_LEVEL_ID => societyMembership.ucinn_ascendv2__Membership_Level_Product__c});
            }

        }

        public virtual void testCreateReviewTransaction() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();

            setUpContacts();
            setUpSocietyMemberships();

            ucinn_ascendv2__Designation__c designation = new ucinn_ascendv2__Designation__c(
                Name = 'Athletics',
                ucinn_ascendv2__Designation_Name__c  = 'Athletics',
                ucinn_portal_Is_Display_On_Portal__c = true
            );
            insert designation;

            System.runAs(contactUser) {
                try {
                    controller.createReviewTransaction(null);
                } catch(Exception e) {}
                try {
                controller.createReviewTransaction(new Map<String, Object>{PORTAL_MembershipControllerBase.PAYMENT_METHOD => 'test', PORTAL_MembershipControllerBase.AMOUNT_CONST => 50, PORTAL_MembershipControllerBase.DESIGNATION_ID => designation.Id});
                } catch(Exception e) {}
            }
        }


        public virtual void testGetMembershipRecords() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();

            controller.getMembershipRecords(null);

            try {
                controller.getMembershipRecords(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'no logged in'});
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            setUpContacts();
            setUpSocietyMemberships();

            System.runAs(contactUser){
                controller.getMembershipRecords(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => '1Giving History',
                                                                        PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'TestActive Membership Table',
                                                                        PORTAL_MembershipControllerBase.SUB_SECTION_NAME => 'TestActive Memberships'});


                Map<String, Object> returnMap = controller.getMembershipRecords(new Map<String, Object>{PORTAL_MembershipControllerBase.PAGE_NAME => 'Memberships',
                                                                                                        PORTAL_MembershipControllerBase.MAIN_SECTION_NAME => 'Membership Table',
                                                                                                        PORTAL_MembershipControllerBase.SUB_SECTION_NAME => 'Active Memberships'});

                System.assert(!((List<Map<String, Object>>)returnMap.get(PORTAL_MembershipControllerBase.MEMBERSHIP_RECORDS)).isEmpty());
            }
        }

        public virtual void testGetMembershipContactInformation() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();

            try {
                controller.getMembershipContactInformation(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            setUpContacts();

            System.runAs(contactUser){
                controller.getMembershipContactInformation(null);
            }
        }

        public virtual void testSaveMembershipRecords() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();
            controller.saveMembershipRecords(null);

            try {
                controller.saveMembershipRecords(new Map<String, Object>{'String' => 'Test'});
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            setUpContacts();
            setUpSocietyMemberships();

            System.runAs(contactUser){
                controller.saveMembershipRecords(new Map<String, Object>{PORTAL_MembershipControllerBase.GLOBAL_MEMBERSHIP_RENEWAL_SOLICIT_OPT_OUT_VALUE => null,
                    PORTAL_MembershipControllerBase.MEMBERSHIPS_TO_UPDATE => new Map<Object, Object>{societyMembership.Id => true}});

                controller.saveMembershipRecords(new Map<String, Object>{PORTAL_MembershipControllerBase.GLOBAL_MEMBERSHIP_RENEWAL_SOLICIT_OPT_OUT_VALUE => true});

                controller.saveMembershipRecords(new Map<String, Object>{PORTAL_MembershipControllerBase.GLOBAL_MEMBERSHIP_RENEWAL_SOLICIT_OPT_OUT_VALUE => true,
                    PORTAL_MembershipControllerBase.MEMBERSHIPS_TO_UPDATE => new Map<Object, Object>{societyMembership.Id => true}});
            }
        }

        public virtual void testGetMembershipBenefitInformation() {
            PORTAL_MembershipControllerBase controller = new PORTAL_MembershipControllerBase();
            controller.saveMembershipRecords(null);

            try {
                controller.saveMembershipRecords(new Map<String, Object>{'String' => 'Test'});
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            setUpContacts();
            setUpSocietyMemberships();
            setUpBenefits();

            System.runAs(contactUser){
                controller.getMembershipBenefitInformation(new Map<String, Object>{PORTAL_MembershipControllerBase.MEMBERSHIP_LEVEL_ID => null});

                controller.getMembershipBenefitInformation(new Map<String, Object>{PORTAL_MembershipControllerBase.MEMBERSHIP_LEVEL_ID => societyMembership.ucinn_ascendv2__Membership_Level_Product__c});
            }
        }
    }


    static testMethod void testinitializeMembershipPurchase() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testinitializeMembershipPurchase();
    }

    static testMethod void testGetMembershipFieldsToPrepopulate() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testGetMembershipFieldsToPrepopulate();
    }

    static testMethod void testCreateReviewTransaction() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testCreateReviewTransaction();
    }


    static testMethod void testGetMembershipRecords() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testGetMembershipRecords();
    }

    static testMethod void testGetMembershipContactInformation() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testGetMembershipContactInformation();
    }

    static testMethod void testSaveMembershipRecords() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testSaveMembershipRecords();
    }

    static testMethod void testGetMembershipBenefit() {
        PORTAL_TestClassFactory.getTestClassFactory().getMembershipControllerTestClass().testGetMembershipBenefitInformation();
    }

}