force-app/main/default/objects/ucinn_ascendv2__Dedupe_Possible_Duplicate__c/ucinn_ascendv2__Dedupe_Possible_Duplicate__c.object-meta.xml
<CustomObject>
    <description>Store all the possible duplicate records in related list.</description>
    <label>Dedupe Possible Duplicate</label>
    <nameField>
        <label>Source Record ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dedupe Possible Duplicates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/ucinn_ascendv2__Interim__c.object-meta.xml
<CustomObject>
    <description>The shell object used for Integration that stores the fields for constituents.</description>
    <label>Interim</label>
    <nameField>
        <label>Interim Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interims</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Interim__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Assigned</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
            <value>
                <fullName>Supervisor Review</fullName>
            </value>
            <value>
                <fullName>Deferred</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Do Not Process</fullName>
            </value>
            <value>
                <fullName>Under Approval</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/ucinn_portal_Interim_Employment__c.object-meta.xml
<CustomObject>
    <label>Interim Employment</label>
    <nameField>
        <label>Interim Employment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Interim Employments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Interim__c.field-meta.xml
<CustomField>
    <fullName>Interim__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Interim</label>
    <referenceTo>ucinn_ascendv2__Interim__c</referenceTo>
    <relationshipLabel>Interim Employments</relationshipLabel>
    <relationshipName>ucinn_portal_Interim_Employments</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Is_Possible_Duplicate_Checked__c.field-meta.xml
<CustomField>
    <fullName>Is_Possible_Duplicate_Checked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Possible Duplicate Checked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Manual_Review_Reason__c.field-meta.xml
<CustomField>
    <fullName>Manual_Review_Reason__c</fullName>
    <label>Manual Review Reason</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Interim_Employment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Manual Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PORTAL_BATCH_ProcessNewInterimEmployment.cls
/*
 * Copyright (c) 2021, UC Innovation, Inc.  All Rights Reserved.
 *                     https://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */

/**
 * batch class that takes an interim employment and checks to see if
 * it can be processed by the next batches
 *
 * @author      Ashley Tran
 * @version 1.0
 * @since   1.0
 */

public with sharing virtual class PORTAL_BATCH_ProcessNewInterimEmployment implements Database.Batchable<sObject>{
    public PORTAL_BATCH_ProcessNewInterimEmployment() {

    }

    /**
     * batch start method that creates the query for the new interim
     * employment records that need to be checked
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     *
     * @return                          the query locator for this batch
     */

    public virtual Database.QueryLocator start(Database.BatchableContext BC) {
        String queryString = 'SELECT Id FROM ucinn_portal_Interim_Employment__c WHERE Status__c = \'New\' AND '
                             + ' Interim__r.ucinn_ascendv2__Status__c = \'Completed\' AND Is_Possible_Duplicate_Checked__c = true';
        return Database.getQueryLocator(queryString);
    }

    /**
     * execution method that will take a list of interim employment records
     * and checks to see if they can be processed or not
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     *
     *
     * @param interimEmploymentList             list of interim employments to process in this execution
     */

    public virtual void execute(Database.BatchableContext BC, List<ucinn_portal_Interim_Employment__c> interimEmploymentList) {
        Map<Id, ucinn_portal_Interim_Employment__c> interimEmploymentMap = new Map<Id, ucinn_portal_Interim_Employment__c>(interimEmploymentList);

        List<ucinn_ascendv2__Dedupe_Possible_Duplicate__c> duplicatesFound = [SELECT Name FROM ucinn_ascendv2__Dedupe_Possible_Duplicate__c WHERE Name IN :interimEmploymentMap.keyset()];
        Set<String> duplicateIdSet = new Set<String>();
        for (ucinn_ascendv2__Dedupe_Possible_Duplicate__c duplicate : duplicatesFound) {
            duplicateIdSet.add(duplicate.Name);
        }
        for (ucinn_portal_Interim_Employment__c interimEmployment : interimEmploymentList) {
            interimEmployment.Status__c = PORTAL_CONST_CommunityUser.PENDING;
            if (duplicateIdSet.contains(String.valueOf(interimEmployment.Id))) {
                interimEmployment.Status__c = PORTAL_CONST_CommunityUser.MANUAL_REVIEW;
                interimEmployment.Manual_Review_Reason__c = 'Possible duplicates found.';
            }
        }
        Database.update(interimEmploymentList, false);
    }

    /**
     * finish method for batch class that calls the pending batch after
     *
     *
     * @author: Ashley Tran
     * @since: 1.0
     */
    public virtual void finish(Database.BatchableContext BC) {
        if (!Test.isRunningTest()) {
            Database.executeBatch(new PORTAL_BATCH_ProcessPendingEmployment());
        }

    }
}