force-app/main/default/objects/ucinn_ascendv2__Address__c/ucinn_ascendv2__Address__c.object-meta.xml
<CustomObject>
    <description>The addresses of the constituent or organization.</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_4__c</fullName>
    <label>Address Line 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__City__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__State__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/ucinn_ascendv2__Address_Relation__c.object-meta.xml
<CustomObject>
    <description>Junction object to associate addresses with constituent or organization.</description>
    <label>Address Relation</label>
    <nameField>
        <label>Address Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Address__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address__c</fullName>
    <label>Address</label>
    <referenceTo>ucinn_ascendv2__Address__c</referenceTo>
    <relationshipLabel>Address Relations</relationshipLabel>
    <relationshipName>Address_Relations_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Address Relations</relationshipLabel>
    <relationshipName>Address_Relations_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Address Removed</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Foreign-Verified</fullName>
                <isActive>false</isActive>
                <label>Foreign-Verified</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <isActive>false</isActive>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Lost Address</fullName>
                <isActive>false</isActive>
                <label>Lost Address</label>
            </value>
            <value>
                <fullName>NCOA Address</fullName>
                <isActive>false</isActive>
                <label>NCOA Address</label>
            </value>
            <value>
                <fullName>Not found-Indv Address Search</fullName>
                <isActive>false</isActive>
                <label>Not found-Indv Address Search</label>
            </value>
            <value>
                <fullName>Parent Address</fullName>
                <isActive>false</isActive>
                <label>Parent Address</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ucinn_ascendv2__Address_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/ucinn_ascendv2__Bypass_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to Bypass Triggers, Process Builders, Workflow, and Validation Rules.</description>
    <label>Bypass Settings</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Process_Builders__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Process_Builders__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all process builders and not execute them</description>
    <inlineHelpText>Check to Bypass process builders and not execute them</inlineHelpText>
    <label>Bypass Process Builders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Triggers__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all apex triggers and not execute them</description>
    <inlineHelpText>Check to Bypass triggers and not execute them</inlineHelpText>
    <label>Bypass Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all object validation rules and not execute them</description>
    <inlineHelpText>Check to Bypass validation rules and not execute them</inlineHelpText>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Workflows__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Workflows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all workflows and not execute them</description>
    <inlineHelpText>Check to Bypass workflows and not execute them</inlineHelpText>
    <label>Bypass Workflows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Designation__c/ucinn_ascendv2__Designation__c.object-meta.xml
<CustomObject>
    <description>The department/unit/fund where the donation will be going to.</description>
    <label>Designation</label>
    <nameField>
        <label>Designation Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Designation__c/fields/ucinn_ascendv2__Designation_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation_Name__c</fullName>
    <inlineHelpText>Displayed on Gift Processing and Giving Detail</inlineHelpText>
    <label>Designation Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Designation__c/fields/ucinn_portal_Is_Display_On_Portal__c.field-meta.xml
<CustomField>
    <fullName>ucinn_portal_Is_Display_On_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display On Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Designation_Detail__c/ucinn_ascendv2__Designation_Detail__c.object-meta.xml
<CustomObject>
    <description>Keeps track of designations for a specific payment/pledge/gift.</description>
    <label>Designation Detail</label>
    <nameField>
        <label>Designation Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Designation Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Designation_Detail__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Designation Details (Constituent)</relationshipLabel>
    <relationshipName>Designation_Details_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Designation_Detail__c/fields/ucinn_ascendv2__Designation__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designation</label>
    <lookupFilter>
        <active>false</active>
        <errorMessage>That Designation is not currently active.</errorMessage>
        <filterItems>
            <field>ucinn_ascendv2__Designation__c.ucinn_ascendv2__Status_Formula__c</field>
            <operation>equals</operation>
            <value>Active</value>
        </filterItems>
        <filterItems>
            <field>ucinn_ascendv2__Designation__c.Name</field>
            <operation>startsWith</operation>
            <value>2, 3, 4, 5, 6, 7, 8, 9</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ucinn_ascendv2__Designation__c</referenceTo>
    <relationshipLabel>Designation Details</relationshipLabel>
    <relationshipName>Designation_Details_Designation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Designation_Detail__c/fields/ucinn_ascendv2__Opportunity__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Opportunity__c</fullName>
    <label>Pledge / Gift</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Designation Details</relationshipLabel>
    <relationshipName>Designation_Details_Opportunity</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Payment__c/ucinn_ascendv2__Payment__c.object-meta.xml
<CustomObject>
    <description>Payment for pledges or gifts.</description>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Payment__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Payment__c/fields/ucinn_ascendv2__Designation__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Designation</label>
    <referenceTo>ucinn_ascendv2__Designation__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments_Designation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Payment__c/fields/ucinn_ascendv2__Designation_Detail__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Designation_Detail__c</fullName>
    <label>Designation Detail</label>
    <referenceTo>ucinn_ascendv2__Designation_Detail__c</referenceTo>
    <relationshipLabel>Payments</relationshipLabel>
    <relationshipName>Payments_Designation_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Payment__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Paid</fullName>
                <default>true</default>
                <label>Paid</label>
            </value>
            <value>
                <fullName>Partial Payment</fullName>
            </value>
            <value>
                <fullName>Early Payment</fullName>
            </value>
            <value>
                <fullName>Written off</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/ucinn_ascendv2__Address_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Additional Home</fullName>
    </customValue>
    <customValue>
        <fullName>Assistant</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Endowment Reporting</fullName>
    </customValue>
    <customValue>
        <fullName>Fifth Home</fullName>
    </customValue>
    <customValue>
        <fullName>Fourth Home</fullName>
    </customValue>
    <customValue>
        <fullName>Home</fullName>
    </customValue>
    <customValue>
        <fullName>Incorrect/Donor Request to Remove</fullName>
    </customValue>
    <customValue>
        <fullName>Matching Gift</fullName>
    </customValue>
    <customValue>
        <fullName>Organization</fullName>
    </customValue>
    <customValue>
        <fullName>Other 1</fullName>
    </customValue>
    <customValue>
        <fullName>Other 2</fullName>
    </customValue>
    <customValue>
        <fullName>Other 3</fullName>
    </customValue>
    <customValue>
        <fullName>Pledge Reminder</fullName>
    </customValue>
    <customValue>
        <fullName>PO Box</fullName>
    </customValue>
    <customValue>
        <fullName>Potential</fullName>
    </customValue>
    <customValue>
        <fullName>Professional Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Receipts</fullName>
    </customValue>
    <customValue>
        <fullName>Seasonal</fullName>
    </customValue>
    <customValue>
        <fullName>Second Business</fullName>
    </customValue>
    <customValue>
        <fullName>Second Home</fullName>
    </customValue>
    <customValue>
        <fullName>Special</fullName>
    </customValue>
    <customValue>
        <fullName>Third Business</fullName>
    </customValue>
    <customValue>
        <fullName>Third Home</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni Association Membership</fullName>
        <isActive>false</isActive>
        <label>Alumni Association Membership</label>
    </customValue>
    <customValue>
        <fullName>Alternate Address</fullName>
        <isActive>false</isActive>
        <label>Alternate Address</label>
    </customValue>
    <customValue>
        <fullName>Shipping</fullName>
        <isActive>false</isActive>
        <label>Shipping</label>
    </customValue>
    <customValue>
        <fullName>Billing</fullName>
        <isActive>false</isActive>
        <label>Billing</label>
    </customValue>
    <customValue>
        <fullName>Campus</fullName>
        <isActive>false</isActive>
        <label>Campus</label>
    </customValue>
    <customValue>
        <fullName>Mailing</fullName>
        <isActive>false</isActive>
        <label>Mailing</label>
    </customValue>
    <masterLabel>Address Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_VF_YearEndTaxReceiptTest.cls
@isTest
global class PORTAL_VF_YearEndTaxReceiptTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public Contact con;
        public User communityUser;
        public Account acct;
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void setupData() {
            ucinn_ascendv2__Bypass_Settings__c bypassSettings = ucinn_ascendv2__Bypass_Settings__c.getInstance();
            bypassSettings.ucinn_ascendv2__Bypass_Process_Builders__c = true;
            bypassSettings.ucinn_ascendv2__Bypass_Triggers__c = true;
            bypassSettings.ucinn_ascendv2__Bypass_Validation_Rules__c = true;
            bypassSettings.ucinn_ascendv2__Bypass_Workflows__c = true;
            bypassSettings = (ucinn_ascendv2__Bypass_Settings__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => bypassSettings});
            insert bypassSettings;

            System.runAs(thisUser) {

                Id profileId = [select id from profile where name=: 'ascend Customer Community User'].id;
                acct = new Account(name = 'ACME Co') ;
                acct = (Account)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => acct});
                insert acct;

                con = new Contact(
                    FirstName= 'Daniel',
                    LastName = 'Test_Contact',
                    AccountId = acct.Id,
                    Email = 'testCommunityUsermig123@test.com'
                );
                con = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => con});
                insert con;

                communityUser = new User(alias = 'comUser',
                                        email = 'testCommunityUsermig123@test.com',
                                        emailencodingkey='UTF-8',
                                        lastname = 'DanielTest',
                                        languagelocalekey='en_US',
                                        localesidkey='en_US',
                                        profileid = profileId,
                                        IsActive = true,
                                        ContactId = con.Id,
                                        timezonesidkey='America/Los_Angeles',
                                        username = 'testCommunityUsermig123!@test.com',
                                        ucinn_portal_Recommend_Type_1__c = 'Law',
                                        ucinn_portal_Recommend_Type_2__c = 'Culture',
                                        ucinn_portal_Recommend_Type_3__c = 'Global');

                communityUser = (User)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => communityUser});
                insert communityUser;

                // address info
                ucinn_ascendv2__Address__c address = new ucinn_ascendv2__Address__c(
                    ucinn_ascendv2__Address_Line_1__c = '1',
                    ucinn_ascendv2__Address_Line_2__c = '2',
                    ucinn_ascendv2__Address_Line_3__c = '3',
                    ucinn_ascendv2__Address_Line_4__c = '4',
                    ucinn_ascendv2__City__c = 'Irvine',
                    ucinn_ascendv2__State__c = 'California',
                    ucinn_ascendv2__Postal_Code__c = '92618'
                );
                address = (ucinn_ascendv2__Address__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => address});
                insert address;

                Id consttiuentAddress = Schema.SObjectType.ucinn_ascendv2__Address_Relation__c.getRecordTypeInfosByDeveloperName()
                        .get('Contact_Address_Relation').getRecordTypeId();

                ucinn_ascendv2__Address_Relation__c addressRelation = new ucinn_ascendv2__Address_Relation__c(
                    Name = 'test',
                    ucinn_ascendv2__Address__c = address.Id,
                    ucinn_ascendv2__Contact__c = con.Id,
                    ucinn_ascendv2__Status__c = 'Current',
                    ucinn_ascendv2__Type__c = 'Home',
                    ucinn_portal_Is_Display_On_Portal__c = true,
                    ucinn_ascendv2__Start_Date__c = Date.parse('10/10/10'),
                    ucinn_ascendv2__End_Date__c = Date.parse('11/11/2099'),
                    RecordTypeId = consttiuentAddress
                );
                addressRelation = (ucinn_ascendv2__Address_Relation__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => addressRelation});
                insert addressRelation;
            }
        }

        public virtual void yearEndTaxLetterTest() {
            setupData();

            RecordType giftOppRecordType = [SELECT Id, Name, Description ,DeveloperName, SobjectType FROM RecordType WHERE SobjectType = 'Opportunity' AND DeveloperName = 'Gift'];

            Opportunity opp = new Opportunity(
                Name = 'Gift',
                StageName = 'Active',
                Amount = 1000,
                CloseDate = Date.parse('10/10/2040'),
                AccountId = acct.Id,
                RecordTypeId = giftOppRecordType.Id,
                ucinn_portal_Is_Display_On_Portal__c = true,
                ucinn_ascendv2__Contact__c = con.Id,
                ucinn_ascendv2__Original_Proposal_ID__c = '12354Test'
            );
            opp = (Opportunity)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => opp});
            insert opp;

            ucinn_ascendv2__Designation__c designation1 = new ucinn_ascendv2__Designation__c(
                Name = 'Athletics',
                ucinn_ascendv2__Designation_Name__c  = 'Athletics',
                ucinn_portal_Is_Display_On_Portal__c = true
            );
            designation1 = (ucinn_ascendv2__Designation__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => designation1});
            insert designation1;

            ucinn_ascendv2__Designation_Detail__c designDetail = new ucinn_ascendv2__Designation_Detail__c(
                ucinn_ascendv2__Opportunity__c = opp.Id,
                ucinn_portal_Is_Display_On_Portal__c = true
            );
            designDetail = (ucinn_ascendv2__Designation_Detail__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => designDetail});
            insert designDetail;

            ucinn_ascendv2__Payment__c  payment1 = new ucinn_ascendv2__Payment__c(
                Name = 'Test',
                ucinn_ascendv2__Tender_Type_for_Gifts__c = 'Stock Gift',
                ucinn_ascendv2__Credit_Date__c = Date.today(),
                ucinn_ascendv2__Contact__c = con.Id,
                ucinn_ascendv2__Designation_Detail__c = designDetail.Id,
                ucinn_ascendv2__Opportunity__c = opp.Id,
                ucinn_ascendv2__Payment_Amount__c = 2500,
                ucinn_ascendv2__Status__c = 'Paid'
            );
            payment1 = (ucinn_ascendv2__Payment__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => payment1});
            insert payment1;

            ucinn_portal_Content_Page__c contentPage = new ucinn_portal_Content_Page__c(
                Name = 'Year end Receipt Page'
            );
            contentPage = (ucinn_portal_Content_Page__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => contentPage});
            insert contentPage;

            ucinn_portal_Content_Module__c contentModule = new ucinn_portal_Content_Module__c(
                Name = 'Receipt Info',
                Content_Module_Metadata__c = '{"imageName":"Year_end_receipt_top_logo","imageAltText":"Sample alt text","addressInfo":"<div>UC Innovation</div><div>2855 Michelle Dr Suite 190</div><div>Irvine, CA 92606</div><div>Test</div>","preTableText":"<p>Dear -!salutation- -!lastName-</p><p>Thank you for your support of the UC Innovation\'s Portal Team</p>"}',
                Content_Page__c = contentPage.Id
            );
            contentModule = (ucinn_portal_Content_Module__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => contentModule});
            insert contentModule;

            PageReference YearEndReceiptPage = Page.PORTAL_YearEndTaxReceipt;
            YearEndReceiptPage.getParameters().put(PORTAL_VF_YearEndTaxReceipt.CONTACT_ID_URL_PARAM, con.Id);
            YearEndReceiptPage.getParameters().put(PORTAL_VF_YearEndTaxReceipt.CONTENT_PAGE_NAME_URL_PARAM, 'Year end Receipt Page');
            YearEndReceiptPage.getParameters().put(PORTAL_VF_YearEndTaxReceipt.CALENDAR_YEAR_URL_PARAM, '2020');

            Test.setCurrentPage(YearEndReceiptPage);

            Test.startTest();

            System.runAs(communityUser) {
                PORTAL_VF_YearEndTaxReceipt yearEndReceiptController = new PORTAL_VF_YearEndTaxReceipt();
            }

            Test.stopTest();
        }
    }

    @isTest
    static void yearEndTaxLetterTest() {
        PORTAL_TestClassFactory.getTestClassFactory().getVF_YearEndTaxReceiptTestClass().yearEndTaxLetterTest();
    }
}