force-app/main/default/objects/ucinn_ascendv2__Address__c/ucinn_ascendv2__Address__c.object-meta.xml
<CustomObject>
    <description>The addresses of the constituent or organization.</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__City__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Country__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__State__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/ucinn_ascendv2__Address_Relation__c.object-meta.xml
<CustomObject>
    <description>Junction object to associate addresses with constituent or organization.</description>
    <label>Address Relation</label>
    <nameField>
        <label>Address Relation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Address Relations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Address__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address__c</fullName>
    <label>Address</label>
    <referenceTo>ucinn_ascendv2__Address__c</referenceTo>
    <relationshipLabel>Address Relations</relationshipLabel>
    <relationshipName>Address_Relations_Address</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Address Relations</relationshipLabel>
    <relationshipName>Address_Relations_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Relation__c/fields/ucinn_ascendv2__Status__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Address Removed</fullName>
            </value>
            <value>
                <fullName>Current</fullName>
            </value>
            <value>
                <fullName>Foreign-Verified</fullName>
                <isActive>false</isActive>
                <label>Foreign-Verified</label>
            </value>
            <value>
                <fullName>Former</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
                <isActive>false</isActive>
                <label>Incomplete</label>
            </value>
            <value>
                <fullName>Lost Address</fullName>
                <isActive>false</isActive>
                <label>Lost Address</label>
            </value>
            <value>
                <fullName>NCOA Address</fullName>
                <isActive>false</isActive>
                <label>NCOA Address</label>
            </value>
            <value>
                <fullName>Not found-Indv Address Search</fullName>
                <isActive>false</isActive>
                <label>Not found-Indv Address Search</label>
            </value>
            <value>
                <fullName>Parent Address</fullName>
                <isActive>false</isActive>
                <label>Parent Address</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Type_Mapping__c/ucinn_ascendv2__Address_Type_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Address Type Mapping</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address_Type_Mapping__c/fields/ucinn_ascendv2__Address_Relation_Type__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Relation_Type__c</fullName>
    <label>Address Relation Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Type_Mapping__c/fields/ucinn_ascendv2__Address_Type_Label_Backend_Message__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Type_Label_Backend_Message__c</fullName>
    <label>Address Type Label Backend Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Type_Mapping__c/fields/ucinn_ascendv2__Backend_Address_Type_API_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Backend_Address_Type_API_Name__c</fullName>
    <label>Backend Address Type API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Type_Mapping__c/fields/ucinn_ascendv2__Object_Address_Field_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Object_Address_Field_Name__c</fullName>
    <label>Object Address Field Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address_Type_Mapping__c/fields/ucinn_ascendv2__Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Object_API_Name__c</fullName>
    <label>Object API Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/ucinn_ascendv2__Org_Wide_Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Org Wide Configuration</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status addresses of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Addresses Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Emails_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Emails_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status emails of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Emails Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Org_Wide_Configuration__c/fields/ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Configure if your school allows a constituent to have multiple current status phones of same type</description>
    <inlineHelpText>Check to enable, or uncheck it to disable.</inlineHelpText>
    <label>Is Multiple Current Phones Enabled</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Reciprocal_Relationships__c/ucinn_ascendv2__Reciprocal_Relationships__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>List of relationships and their reciprocal relationships</description>
    <label>Reciprocal Relationships</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Reciprocal_Relationships__c/fields/ucinn_ascendv2__Reciprocal__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Reciprocal__c</fullName>
    <label>Reciprocal</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator__c/ucinn_ascendv2__Service_Indicator__c.object-meta.xml
<CustomObject>
    <description>Type of action assigned to a constituent that is related to how to approach the constituent based on the constituent&apos;s preferences.</description>
    <label>Service Indicator</label>
    <nameField>
        <label>Service Indicator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Indicators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator__c/fields/ucinn_ascendv2__Contact__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Constituent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Service Indicators</relationshipLabel>
    <relationshipName>Service_Indicators_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator__c/fields/ucinn_ascendv2__Is_Active__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Is_Active__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator__c/fields/ucinn_ascendv2__Service_Indicator_Value__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Service_Indicator_Value__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Indicator Value</label>
    <referenceTo>ucinn_ascendv2__Service_Indicator_Value__c</referenceTo>
    <relationshipLabel>Service Indicators</relationshipLabel>
    <relationshipName>Service_Indicators_Service_Indicator_Val</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator_Value__c/ucinn_ascendv2__Service_Indicator_Value__c.object-meta.xml
<CustomObject>
    <description>List of preferences that a constituent may have, such as Do Not Call, Do Not Solicit, etc.</description>
    <label>Service Indicator Value</label>
    <nameField>
        <label>Service Indicator Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Indicator Values</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Service_Indicator_Value__c/fields/ucinn_ascendv2__Code__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Code__c</fullName>
    <externalId>true</externalId>
    <label>Code</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/ucinn_portal_Zone__c.object-meta.xml
<CustomObject>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Zone__c/fields/Is_Display_on_Portal__c.field-meta.xml
<CustomField>
    <fullName>Is_Display_on_Portal__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Is Display on Portal</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/fields/Search_Radius__c.field-meta.xml
<CustomField>
    <fullName>Search_Radius__c</fullName>
    <defaultValue>50</defaultValue>
    <label>Search Radius</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Zone__c/recordTypes/Club.recordType-meta.xml
<RecordType>
    <fullName>Club</fullName>
    <active>true</active>
    <label>Club</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Zone__c/recordTypes/Group.recordType-meta.xml
<RecordType>
    <fullName>Group</fullName>
    <active>true</active>
    <label>Group</label>
</RecordType>

force-app/main/default/classes/PORTAL_BATCH_AddZoneMembershipsTest.cls
@isTest
public with sharing class PORTAL_BATCH_AddZoneMembershipsTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void testBatch() {

            ucinn_ascendv2__Org_Wide_Configuration__c orgSettings = new ucinn_ascendv2__Org_Wide_Configuration__c();
            orgSettings.Name = 'Default Org Wide Config';
            orgSettings.ucinn_ascendv2__Is_Multiple_Current_Addresses_Enabled__c = true;
            orgSettings.ucinn_ascendv2__Is_Multiple_Current_Phones_Enabled__c = true;
            orgSettings.ucinn_ascendv2__Is_Multiple_Current_Emails_Enabled__c = true;
            orgSettings = (ucinn_ascendv2__Org_Wide_Configuration__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => orgSettings});
            insert orgSettings;

            ucinn_ascendv2__Address_Type_Mapping__c addressSetting = new ucinn_ascendv2__Address_Type_Mapping__c(name='Contact_Mailing', ucinn_ascendv2__Address_Relation_Type__c = 'Home',
                                                                                                                    ucinn_ascendv2__Address_Type_Label_Backend_Message__c = 'home',
                                                                                                                    ucinn_ascendv2__Backend_Address_Type_API_Name__c = 'Home',
                                                                                                                    ucinn_ascendv2__Object_API_Name__c = 'Contact',
                                                                                                                    ucinn_ascendv2__Object_Address_Field_Name__c = 'MailingAddress');
            ucinn_ascendv2__Address_Type_Mapping__c addressSetting2 = new ucinn_ascendv2__Address_Type_Mapping__c(name='Contact_Other', ucinn_ascendv2__Address_Relation_Type__c = 'Business',
                                                                                                                    ucinn_ascendv2__Address_Type_Label_Backend_Message__c = 'business',
                                                                                                                    ucinn_ascendv2__Backend_Address_Type_API_Name__c = 'Business',
                                                                                                                    ucinn_ascendv2__Object_API_Name__c = 'Contact',
                                                                                                                    ucinn_ascendv2__Object_Address_Field_Name__c = 'OtherAddress');
            addressSetting = (ucinn_ascendv2__Address_Type_Mapping__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => addressSetting});
            addressSetting2 = (ucinn_ascendv2__Address_Type_Mapping__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => addressSetting2});
            insert addressSetting;
            insert addressSetting2;

            ucinn_ascendv2__Reciprocal_Relationships__c relationshipSetting = new ucinn_ascendv2__Reciprocal_Relationships__c(Name = 'Spouse', ucinn_ascendv2__Reciprocal__c = 'Spouse');
            relationshipSetting = (ucinn_ascendv2__Reciprocal_Relationships__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => relationshipSetting});
            insert relationshipSetting;


            ucinn_portal_Zone__c zone = new ucinn_portal_Zone__c();
            zone.Geolocation__longitude__s = 50;
            zone.Geolocation__latitude__s = 50;
            zone.Is_Display_On_Portal__c = true;
            zone.Search_Radius__c = 200;
            zone.RecordTypeId = Schema.SObjectType.ucinn_portal_Zone__c.getRecordTypeInfosByDeveloperName().get('Club').getRecordTypeId();
            zone = (ucinn_portal_Zone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => zone});
            insert zone;

            ucinn_portal_Zone__c secondZone = new ucinn_portal_Zone__c();
            secondZone.Geolocation__longitude__s = 80;
            secondZone.Geolocation__latitude__s = 80;
            secondZone.Is_Display_On_Portal__c = true;
            secondZone.Search_Radius__c = 200;
            secondZone.RecordTypeId = Schema.SObjectType.ucinn_portal_Zone__c.getRecordTypeInfosByDeveloperName().get('Group').getRecordTypeId();
            secondZone = (ucinn_portal_Zone__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => secondZone});
            insert secondZone;

            Contact cont = new Contact();
            cont.LastName = 'Test';
            cont.ucinn_ascendv2__Contact_Type__c = 'Alumni';
            cont = (Contact)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => cont});
            insert cont;

            ucinn_ascendv2__Address__c address = new ucinn_ascendv2__Address__c();
            address.ucinn_ascendv2__Address_Line_1__c = '2855 Michelle Drive';
            address.ucinn_ascendv2__City__c = 'Irvine';
            address.ucinn_ascendv2__State__c = 'CA';
            address.ucinn_ascendv2__Country__c = 'United States';
            address.ucinn_ascendv2__Postal_Code__c = '92606';
            address.ucinn_ascendv2__Location__longitude__s = 50;
            address.ucinn_ascendv2__Location__latitude__s = 50;
            address = (ucinn_ascendv2__Address__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => address});
            insert address;

            ucinn_ascendv2__Address_Relation__c relation = new ucinn_ascendv2__Address_Relation__c();
            relation.ucinn_ascendv2__Status__c = 'Current';
            relation.ucinn_ascendv2__Address__c =  address.Id;
            relation.ucinn_ascendv2__Contact__c = cont.Id;
            relation = (ucinn_ascendv2__Address_Relation__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => relation});
            insert relation;

            ucinn_ascendv2__Service_Indicator_Value__c indicatorValue = new ucinn_ascendv2__Service_Indicator_Value__c();
            indicatorValue.ucinn_ascendv2__Code__c = 'DNC';
            indicatorValue = (ucinn_ascendv2__Service_Indicator_Value__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => indicatorValue});
            insert indicatorValue;

            ucinn_ascendv2__Service_Indicator__c indicator = new ucinn_ascendv2__Service_Indicator__c();
            indicator.ucinn_ascendv2__Contact__c = cont.Id;
            indicator.ucinn_ascendv2__Is_Active__c = true;
            indicator.ucinn_ascendv2__Service_Indicator_Value__c = indicatorValue.Id;
            indicator = (ucinn_ascendv2__Service_Indicator__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => indicator});
            insert indicator;

            ucinn_ascendv2__Service_Indicator_Value__c indicatorValue2 = new ucinn_ascendv2__Service_Indicator_Value__c();
            indicatorValue2.ucinn_ascendv2__Code__c = 'LTC';
            indicatorValue2 = (ucinn_ascendv2__Service_Indicator_Value__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => indicatorValue2});
            insert indicatorValue2;

            ucinn_ascendv2__Service_Indicator__c indicator2 = new ucinn_ascendv2__Service_Indicator__c();
            indicator2.ucinn_ascendv2__Contact__c = cont.Id;
            indicator2.ucinn_ascendv2__Is_Active__c = true;
            indicator2.ucinn_ascendv2__Service_Indicator_Value__c = indicatorValue2.Id;
            indicator2 = (ucinn_ascendv2__Service_Indicator__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => indicator2});
            insert indicator2;

            Test.startTest();
            Database.executeBatch(new PORTAL_BATCH_AddZoneMemberships());
            Test.stopTest();

        }
    }

    @isTest
    public static void testBatch() {
        PORTAL_TestClassFactory.getTestClassFactory().getAddZoneMembershipTestClass().testBatch();
    }
}