force-app/main/default/objects/ucinn_ascendv2__Address__c/ucinn_ascendv2__Address__c.object-meta.xml
<CustomObject>
    <description>The addresses of the constituent or organization.</description>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Address_Line_4__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Address_Line_4__c</fullName>
    <label>Address Line 4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__City__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__City__c</fullName>
    <label>City</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Country__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Country__c</fullName>
    <label>Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Address__c/fields/ucinn_ascendv2__State__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__State__c</fullName>
    <label>State</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/ucinn_portal_Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Address_Line_1__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_1__c</fullName>
    <label>Address Line 1</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Address_Line_2__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_2__c</fullName>
    <label>Address Line 2</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Address_Line_3__c.field-meta.xml
<CustomField>
    <fullName>Address_Line_3__c</fullName>
    <label>Address Line 3</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Job__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <length>75</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PORTAL_CONST_GeocodingFields.cls
public with sharing class PORTAL_CONST_GeocodingFields {

    public static final String STREET_FIELDS_KEY = 'streetFields';
    public static final String OTHER_FIELDS_KEY = 'otherFields';
    public static final String ADDRESS_API_NAME = 'ucinn_ascendv2__Address__c';
    public static final String JOB_API_NAME = 'ucinn_portal_Job__c';
    public static final Set<String> ADDRESS_GEOLOCATION_FIELDS = new Set<String>{'ucinn_ascendv2__Location__longitude__s', 'ucinn_ascendv2__Location__latitude__s'};
    public static final Set<String> JOB_GEOLOCATION_FIELDS = new Set<String>{'Geolocation__longitude__s', 'Geolocation__latitude__s'};
    public static final Map<String, List<String>> JOB_FIELDS = new Map<String, List<String>>{STREET_FIELDS_KEY => new List<String>{'Address_Line_1__c', 'Address_Line_2__c', 'Address_Line_3__c'},
                                                                                           OTHER_FIELDS_KEY => new List<String>{'City__c', 'State__c', 'Country__c', 'Postal_Code__c'}};
    public static final Map<String, List<String>> ADDRESS_FIELDS = new Map<String, List<String>>{STREET_FIELDS_KEY => new List<String>{'ucinn_ascendv2__Address_Line_1__c', 'ucinn_ascendv2__Address_Line_2__c', 'ucinn_ascendv2__Address_Line_3__c', 'ucinn_ascendv2__Address_Line_4__c'},
                                                                                           OTHER_FIELDS_KEY => new List<String>{'ucinn_ascendv2__City__c', 'ucinn_ascendv2__State__c', 'ucinn_ascendv2__Country__c', 'ucinn_ascendv2__Postal_Code__c'}};
}