force-app/main/default/objects/ucinn_portal_Listing__c/ucinn_portal_Listing__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Portal_Zone__c.field-meta.xml
<CustomField>
    <fullName>Portal_Zone__c</fullName>
    <label>Portal Zone</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Portal_Zone</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Recommend_Type_1__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Type_1__c</fullName>
    <label>Recommend Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Content_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Recommend_Type_2__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Type_2__c</fullName>
    <label>Recommend Type 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Content_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Recommend_Type_3__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Type_3__c</fullName>
    <label>Recommend Type 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Content_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Recommend_Type_4__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Type_4__c</fullName>
    <label>Recommend Type 4</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Content_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Recommend_Type_5__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Type_5__c</fullName>
    <label>Recommend Type 5</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Content_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/globalValueSets/Content_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arts</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Breakthroughs</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Child Development</fullName>
    </customValue>
    <customValue>
        <fullName>Computation</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Emerging Treatments</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Environment</fullName>
    </customValue>
    <customValue>
        <fullName>Family Care</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Humanities</fullName>
    </customValue>
    <customValue>
        <fullName>K-12 Education</fullName>
    </customValue>
    <customValue>
        <fullName>Language</fullName>
    </customValue>
    <customValue>
        <fullName>Law</fullName>
    </customValue>
    <customValue>
        <fullName>Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Mind and Brain</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Wellness</fullName>
    </customValue>
    <customValue>
        <fullName>Physical Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Politics</fullName>
    </customValue>
    <customValue>
        <fullName>Public Health</fullName>
    </customValue>
    <customValue>
        <fullName>Public Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <customValue>
        <fullName>Space</fullName>
    </customValue>
    <masterLabel>Content Type</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/Portal_Zone.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>All</fullName>
        <default>true</default>
        <label>All</label>
    </customValue>
    <customValue>
        <fullName>Main</fullName>
    </customValue>
    <customValue>
        <fullName>Alumni Club of Irvine</fullName>
    </customValue>
    <masterLabel>Portal Zone</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_LWC_ListingControllerTest.cls
@isTest
public class PORTAL_LWC_ListingControllerTest {
    public virtual class TestClass extends PORTAL_TestClassBase{
        public PORTAL_UTIL_TestClassUtil testClassUtil = new PORTAL_UTIL_TestClassUtil();

        public virtual void testGetListings() {
            PORTAL_LWC_ListingController.SERVER_getListings(null);

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getListings(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getListings(null);
            } catch (Exception e) {
                System.debug(e);
            }
        }

        public virtual void testGetListingConfigurations() {
            PORTAL_LWC_ListingController.SERVER_getListingConfigurations(null);

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getListingConfigurations(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getListingConfigurations(null);
            } catch (Exception e) {
                System.debug(e);
            }
        }

        public virtual void testGetListingButtonText() {
            PORTAL_LWC_ListingController.SERVER_getListingButtonText(null);

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getListingButtonText(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getListingButtonText(null);
            } catch (Exception e) {
                System.debug(e);
            }
        }

        public virtual void testUpdateRecommmedationEngine() {
            Id recordTypeId = Schema.SObjectType.ucinn_portal_Listing__c.getRecordTypeInfosByDeveloperName().get(PORTAL_CONST_Listing.EVENT).getRecordTypeId();

            ucinn_portal_Listing__c testListing = new ucinn_portal_Listing__c(Recommend_Type_1__c = 'Law',
                                                                                Recommend_Type_2__c = 'Culture',
                                                                                Recommend_Type_3__c = 'Global',
                                                                                Recommend_Type_4__c = 'History',
                                                                                Recommend_Type_5__c = 'Space',
                                                                                RecordTypeId = recordTypeId,
                                                                                Portal_Zone__c = 'All',
                                                                                Name = 'a');
            testListing = (ucinn_portal_Listing__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => testListing});
            insert testListing;

            PORTAL_LWC_ListingController.SERVER_updateRecommendationEngine(new Map<String, Object>{PORTAL_CONST_ActionOnContent.CONTENT_ID_KEY => testListing.Id, PORTAL_CONST_ActionOnContent.IP_ADDRESS_KEY => ''});

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_updateRecommendationEngine(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_updateRecommendationEngine(null);
            } catch (Exception e) {
                System.debug(e);
            }
        }

        public virtual void testUpdateActionOnContent() {
            Id recordTypeId = Schema.SObjectType.ucinn_portal_Listing__c.getRecordTypeInfosByDeveloperName().get(PORTAL_CONST_Listing.EVENT).getRecordTypeId();

            ucinn_portal_Listing__c testListing = new ucinn_portal_Listing__c(Recommend_Type_1__c = 'Law',
                                                                                Recommend_Type_2__c = 'Culture',
                                                                                Recommend_Type_3__c = 'Global',
                                                                                Recommend_Type_4__c = 'History',
                                                                                Recommend_Type_5__c = 'Space',
                                                                                RecordTypeId = recordTypeId,
                                                                                Portal_Zone__c = 'All',
                                                                                Name = 'a');
            testListing = (ucinn_portal_Listing__c)testClassUtil.populateRequiredFieldsOnObject(new Map<String, Object>{PORTAL_UTIL_TestClassUtil.S_OBJECT_TO_POPULATE_KEY => testListing});
            insert testListing;

            PORTAL_LWC_ListingController.SERVER_updateActionOnContent(new Map<String, Object>{PORTAL_ListingControllerBase.ACTION_TO_TAKE_KEY => 'bookmark', PORTAL_CONST_ActionOnContent.LISTING_ID_KEY => testListing.Id, PORTAL_CONST_ActionOnContent.IP_ADDRESS_KEY => ''});
            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_updateActionOnContent(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_updateActionOnContent(null);
            } catch (Exception e) {
                System.debug(e);
            }
        }

        public virtual void testGetFrontEndDataMap() {
            PORTAL_LWC_ListingController.SERVER_getFrontEndDataMap(null);
            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.AURA_HANDLED_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getFrontEndDataMap(null);
            } catch (AuraHandledException ahe) {
                System.debug(ahe);
            }

            try {
                PORTAL_CommunityUtils.testExceptionType = PORTAL_CommunityUtils.NULL_POINTER_EXCEPTION;
                PORTAL_LWC_ListingController.SERVER_getFrontEndDataMap(null);
            } catch (Exception e) {
                System.debug(e);
            }
        }
    }

    static testMethod void testGetListings() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcListingControllerTestClass().testGetListings();
    }

    static testMethod void testGetListingConfigurations() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcListingControllerTestClass().testGetListingConfigurations();
    }

    static testMethod void testGetListingButtonText() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcListingControllerTestClass().testGetListingButtonText();
    }

    static testMethod void testUpdateRecommmedationEngine() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcListingControllerTestClass().testUpdateRecommmedationEngine();
    }

    static testMethod void testUpdateActionOnContent() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcListingControllerTestClass().testUpdateActionOnContent();
    }

    static testMethod void testGetFrontEndDataMap() {
        PORTAL_TestClassFactory.getTestClassFactory().getLwcListingControllerTestClass().testGetFrontEndDataMap();
    }
}