force-app/main/default/objects/ucinn_portal_Listing__c/ucinn_portal_Listing__c.object-meta.xml
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Article_Length__c.field-meta.xml
<CustomField>
    <fullName>Article_Length__c</fullName>
    <label>Article Length</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Short ( &lt; 1000 words)</fullName>
            </value>
            <value>
                <fullName>Medium (1000 - 5000 words)</fullName>
            </value>
            <value>
                <fullName>Long ( &gt; 5000 words)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Onsite</fullName>
            </value>
            <value>
                <fullName>Careers</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US</fullName>
                <label>United States</label>
            </value>
            <value>
                <fullName>AF</fullName>
                <label>Afghanistan</label>
            </value>
            <value>
                <fullName>AL</fullName>
                <label>Albania</label>
            </value>
            <value>
                <fullName>AG</fullName>
                <label>Algeria</label>
            </value>
            <value>
                <fullName>AQ</fullName>
                <label>American Samoa</label>
            </value>
            <value>
                <fullName>AN</fullName>
                <label>Andorra</label>
            </value>
            <value>
                <fullName>AO</fullName>
                <label>Angola</label>
            </value>
            <value>
                <fullName>AV</fullName>
                <label>Anguilla</label>
            </value>
            <value>
                <fullName>AY</fullName>
                <label>Antarctica</label>
            </value>
            <value>
                <fullName>AC</fullName>
                <label>Antigua and Barbuda</label>
            </value>
            <value>
                <fullName>AR</fullName>
                <label>Argentina</label>
            </value>
            <value>
                <fullName>AM</fullName>
                <label>Armenia</label>
            </value>
            <value>
                <fullName>AB</fullName>
                <label>Aruba</label>
            </value>
            <value>
                <fullName>AT</fullName>
                <label>Ashmore and Cartier</label>
            </value>
            <value>
                <fullName>AS</fullName>
                <label>Australia</label>
            </value>
            <value>
                <fullName>AU</fullName>
                <label>Austria</label>
            </value>
            <value>
                <fullName>AZ</fullName>
                <label>Azerbaijan</label>
            </value>
            <value>
                <fullName>BF</fullName>
                <label>Bahamas</label>
            </value>
            <value>
                <fullName>BA</fullName>
                <label>Bahrain</label>
            </value>
            <value>
                <fullName>BJ</fullName>
                <label>Bali</label>
            </value>
            <value>
                <fullName>BG</fullName>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>BB</fullName>
                <label>Barbados</label>
            </value>
            <value>
                <fullName>BO</fullName>
                <label>Belarus</label>
            </value>
            <value>
                <fullName>BE</fullName>
                <label>Belgium</label>
            </value>
            <value>
                <fullName>BZ</fullName>
                <label>Belize</label>
            </value>
            <value>
                <fullName>BN</fullName>
                <label>Benin</label>
            </value>
            <value>
                <fullName>BD</fullName>
                <label>Bermuda</label>
            </value>
            <value>
                <fullName>BT</fullName>
                <label>Bhutan</label>
            </value>
            <value>
                <fullName>BL</fullName>
                <label>Bolivia</label>
            </value>
            <value>
                <fullName>BH</fullName>
                <label>Bosnia Herzegovina</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Format__c.field-meta.xml
<CustomField>
    <fullName>Format__c</fullName>
    <label>Format</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Article</fullName>
            </value>
            <value>
                <fullName>Video</fullName>
            </value>
            <value>
                <fullName>Podcast</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Geolocation__c.field-meta.xml
<CustomField>
    <fullName>Geolocation__c</fullName>
    <label>Geolocation</label>
    <scale>15</scale>
    <type>Location</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Postal_Code__c</fullName>
    <label>Postal Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Recommend_Type_1__c.field-meta.xml
<CustomField>
    <fullName>Recommend_Type_1__c</fullName>
    <label>Recommend Type 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Content_Type</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Private</fullName>
            </value>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Unpublished</fullName>
            </value>
            <value>
                <fullName>Published</fullName>
            </value>
            <value>
                <fullName>Temporary</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Scheduled</fullName>
            </value>
            <value>
                <fullName>Unscheduled</fullName>
            </value>
            <value>
                <fullName>Incomplete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Event.recordType-meta.xml
<RecordType>
    <fullName>Event</fullName>
    <active>true</active>
    <label>Event</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/News.recordType-meta.xml
<RecordType>
    <fullName>News</fullName>
    <active>true</active>
    <label>News</label>
</RecordType>

force-app/main/default/objects/ucinn_portal_Listing__c/recordTypes/Newsletter.recordType-meta.xml
<RecordType>
    <fullName>Newsletter</fullName>
    <active>true</active>
    <label>Newsletter</label>
</RecordType>

force-app/main/default/globalValueSets/Content_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Arts</fullName>
    </customValue>
    <customValue>
        <fullName>Biology</fullName>
    </customValue>
    <customValue>
        <fullName>Breakthroughs</fullName>
    </customValue>
    <customValue>
        <fullName>Business</fullName>
    </customValue>
    <customValue>
        <fullName>Child Development</fullName>
    </customValue>
    <customValue>
        <fullName>Computation</fullName>
    </customValue>
    <customValue>
        <fullName>Culture</fullName>
    </customValue>
    <customValue>
        <fullName>Economics</fullName>
    </customValue>
    <customValue>
        <fullName>Emerging Treatments</fullName>
    </customValue>
    <customValue>
        <fullName>Engineering</fullName>
    </customValue>
    <customValue>
        <fullName>Entrepreneurship</fullName>
    </customValue>
    <customValue>
        <fullName>Environment</fullName>
    </customValue>
    <customValue>
        <fullName>Family Care</fullName>
    </customValue>
    <customValue>
        <fullName>Global</fullName>
    </customValue>
    <customValue>
        <fullName>Higher Education</fullName>
    </customValue>
    <customValue>
        <fullName>History</fullName>
    </customValue>
    <customValue>
        <fullName>Humanities</fullName>
    </customValue>
    <customValue>
        <fullName>K-12 Education</fullName>
    </customValue>
    <customValue>
        <fullName>Language</fullName>
    </customValue>
    <customValue>
        <fullName>Law</fullName>
    </customValue>
    <customValue>
        <fullName>Markets</fullName>
    </customValue>
    <customValue>
        <fullName>Mathematics</fullName>
    </customValue>
    <customValue>
        <fullName>Medicine</fullName>
    </customValue>
    <customValue>
        <fullName>Mind and Brain</fullName>
    </customValue>
    <customValue>
        <fullName>Personal Wellness</fullName>
    </customValue>
    <customValue>
        <fullName>Physical Sciences</fullName>
    </customValue>
    <customValue>
        <fullName>Politics</fullName>
    </customValue>
    <customValue>
        <fullName>Public Health</fullName>
    </customValue>
    <customValue>
        <fullName>Public Policy</fullName>
    </customValue>
    <customValue>
        <fullName>Religion</fullName>
    </customValue>
    <masterLabel>Content Type</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/PORTAL_CONST_Listing.cls
/*
 * Copyright (c) 2021, UC Innovation, Inc.  All Rights Reserved.
 *                     https://www.ucinnovation.com
 *
 * This source code is licensed, not sold, and is subject to a written
 * license agreement.  Among other things, no portion of this source
 * code may be copied, transmitted, disclosed, displayed, distributed,
 * translated, used as the basis for a derivative work, or used, in
 * whole or in part, for any program or purpose other than its intended
 * use in compliance with the license agreement as part of UC Innovation's
 * software.  This source code and certain of the algorithms contained
 * within it are confidential trade secrets of UC Innovation, Inc.
 * and may not be used as the basis for any other
 * software, hardware, product or service.
 */

/**
 * Provides constant values for Listing Lightning Web Component controllers.
 *
 * @author      Andrew Leon
 * @version     1.0
 */
global without sharing class PORTAL_CONST_Listing {
    global final static String CATEGORY_API_NAME = 'Category__c';
    global final static String COUNTRY_API_NAME = 'Country__c';
    global final static String TOPIC_API_NAME = 'Recommend_Type_1__c';
    global final static String ARTICLE_LENGTH_API_NAME = 'Article_Length__c';
    global final static String FORMAT_API_NAME = 'Format__c';
    global final static String STATUS_API_NAME = 'Status__c';
    global final static String STATUS_PUBLISHED = 'Published';
    global final static String STATUS_DRAFT = 'Draft';
    global final static String LISTING = 'ucinn_portal_Listing__c';
    global final static String RECORD_TYPE_ID = 'RecordTypeId';
    global final static String EVENT = 'Event';
    global final static String NEWSLETTER = 'Newsletter';
    global final static String NEWS = 'News';

    global static final String LISTING_STATUS_TEMPORARY = 'Temporary';
    global static final String LISTING_STATUS_PENDING = 'Pending';
    global final static String LISTING_STATUS_PUBLISHED = 'Published';

    global final static String AURA_HANDLED_EXCEPTION_MESSAGE  = 'I\'m just here to get the stack trace.';
    global final static String EMPTY_RECORD_QUERY_RESULT_ERROR = 'Could not retrieve the Record ID\'s corresponding ' +
                                                                 'Listing. Make sure the Record ID is valid and the ' +
                                                                 'current user can view the associated Listing.';

    global final static String DEBUG_KEY_NAME = 'Debug_AES_Key'; // switch once it's in COMMUNITY_UTILS
    global final static String INVALID_RECORD_ID_ERROR         = 'Please provide a valid Record ID.';
    global final static String INVALID_RECORD_NAME_ERROR = 'Please provide a valid Record Name.';

    global final static String MODIFY_REGISTRATION_TEXT_DEFAULT = 'Modify Registration';
    global final static String REGISTER_TEXT_DEFAULT = 'Register';
    global final static String SOLD_OUT_TEXT_DEFAULT = 'Sold Out';
    global final static String VIEW_EVENT_TEXT_DEFAULT = 'View Event';
    global final static String LOOK_WHOS_COMING_TEXT_DEFAULT = 'Look Who\'s Coming';

    global final static String ORG_SETTING_EVENT_MODIFY_REGISTRATION_TEXT = 'Event_Modify_Registration_Text';
    global final static String ORG_SETTING_EVENT_REGISTER_TEXT = 'Event_Register_Text';
    global final static String ORG_SETTING_EVENT_SOLD_OUT_TEXT = 'Event_Sold_Out_Text';
    global final static String ORG_SETTING_EVENT_VIEW_EVENT_TEXT = 'Event_View_Event_Text';
    global final static String ORG_SETTING_EVENT_LOOK_WHOS_COMING_TEXT  = 'Event_Look_Whos_Coming_Text';

    global final static List<String> ORG_SETTING_BUTTON_TEXT_DEVELOPER_NAMES = new List<String>{ORG_SETTING_EVENT_REGISTER_TEXT,
                                                                                                ORG_SETTING_EVENT_MODIFY_REGISTRATION_TEXT,
                                                                                                ORG_SETTING_EVENT_SOLD_OUT_TEXT,
                                                                                                ORG_SETTING_EVENT_VIEW_EVENT_TEXT,
                                                                                                ORG_SETTING_EVENT_LOOK_WHOS_COMING_TEXT};

    global final static Map<PORTAL_AddressWrapper.ADDRESS_FIELD, String> LOCATION_FIELD_MAPPING = new Map<PORTAL_AddressWrapper.ADDRESS_FIELD, String>{
        PORTAL_AddressWrapper.ADDRESS_FIELD.STREET1 => 'Street__c',
        PORTAL_AddressWrapper.ADDRESS_FIELD.CITY => 'City__c',
        PORTAL_AddressWrapper.ADDRESS_FIELD.STATE => 'State__c',
        PORTAL_AddressWrapper.ADDRESS_FIELD.COUNTRY => 'Country__c',
        PORTAL_AddressWrapper.ADDRESS_FIELD.POSTCODE => 'Postal_Code__c',
        PORTAL_AddressWrapper.ADDRESS_FIELD.GEOLOCATION => 'Geolocation__c'
    };
}