force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/ucinn_ascendv2__Bypass_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Custom Setting to Bypass Triggers, Process Builders, Workflow, and Validation Rules.</description>
    <label>Bypass Settings</label>
</CustomObject>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Process_Builders__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Process_Builders__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all process builders and not execute them</description>
    <inlineHelpText>Check to Bypass process builders and not execute them</inlineHelpText>
    <label>Bypass Process Builders</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Triggers__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Triggers__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all apex triggers and not execute them</description>
    <inlineHelpText>Check to Bypass triggers and not execute them</inlineHelpText>
    <label>Bypass Triggers</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Validation_Rules__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Validation_Rules__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all object validation rules and not execute them</description>
    <inlineHelpText>Check to Bypass validation rules and not execute them</inlineHelpText>
    <label>Bypass Validation Rules</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ucinn_ascendv2__Bypass_Settings__c/fields/ucinn_ascendv2__Bypass_Workflows__c.field-meta.xml
<CustomField>
    <fullName>ucinn_ascendv2__Bypass_Workflows__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This is to Bypass all workflows and not execute them</description>
    <inlineHelpText>Check to Bypass workflows and not execute them</inlineHelpText>
    <label>Bypass Workflows</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PORTAL_TestClassBase.cls
public abstract class PORTAL_TestClassBase {
    public User thisUser;
    public PORTAL_TestClassBase() {
        thisUser = [SELECT Id,Name FROM User WHERE ID = :UserInfo.getUserId()];

        System.runAs(thisUser){
            insert new ucinn_ascendv2__Bypass_Settings__c(SetupOwnerId = UserInfo.getOrganizationId(),
                                                          ucinn_ascendv2__Bypass_Process_Builders__c = true,
                                                          ucinn_ascendv2__Bypass_Triggers__c = true,
                                                          ucinn_ascendv2__Bypass_Validation_Rules__c = true,
                                                          ucinn_ascendv2__Bypass_Workflows__c = true);

            UserRole usrRole = new UserRole(Name = 'ascendUserRole');
            insert usrRole;

            thisUser.UserRoleId = usrRole.Id;
            update thisUser;
        }

    }
}